### ISSUE TITLE
Problem with MCP23S17GpioExample at start

### ISSUE THREAD

**Issue by interdigitec** [Pi4J/pi4j-v1#104]
Hi,
Some time whe the program MCP23S17GpioExample.java starts, the listener send the following message: --> GPIO PIN STATE CHANGE: "MyInput-B4" <GPIO B4> = HIGH
I suppose that the listener start and the provision gpio input pins from MCP23S17 is not finish.

**Comment by savageautomate** [comment]
fixed in: https://github.com/Pi4J/pi4j/commit/a17b089c43ab37cbc82113bf969aee1abcbd32c7

I was not able to reproduce; however the read/write operations were not synchronized.  Added synchronization thinking that may help.
