### ISSUE TITLE
MCP23S17GpioProvider use only default address 0x40

### ISSUE THREAD

**Issue by interdigitec** [Pi4J/pi4j-v1#106]
Hi,
In case of multiple MCP23S17, even If the address (0x40, 0x41, 0x42, ...) is send to the MCP23S17GpioProvider, it use all the time the default address 0x40.

BR
Reinhard

**Comment by interdigitec** [comment]
Hi,
I take a look at the source code:
the spi address is used in write and read. Instead using the spiAddress comming from the MCP23S17GpioProvider, it use always the DEFAULT_ADDRESS (0x40).

BR
Reinhard

**Comment by interdigitec** [comment]
Hi,
The write in the register 'REGISTER_IOCON' should be outside from the MCP23S17GpioProvider if using multiple MCP23S17 chips. The bit 3 HAEN: Hardware Address Enable bit should be set to 1.

BR
Reinhard

**Comment by savageautomate** [comment]
I have implemented your suggestions, please review and let me know if anything else is needed.  Thanks, Robert
