### ISSUE TITLE
ArrayIndexOutOfBoundsException in PCF8574GpioProvider#setState()

### ISSUE THREAD

**Issue by agawecki** [Pi4J/pi4j-v1#107]
PCF8574GpioProvider#setState() causes an ArrayIndexOutOfBoundsException if all pins are LOW.

This is because BitSet#toByteArray() returns the empty array if all bits are zero.

**Comment by agawecki** [comment]
just opened a pull request fixing the issue

**Comment by savageautomate** [comment]
pull request merged into 'develop' branch
