### ISSUE TITLE
Spi wrapper issues

### ISSUE THREAD

**Issue by PoJD** [Pi4J/pi4j-v1#111]
- wiringPi uses 8bit unsigned char, so using 8 bit signed byte from java to map to that is not optimal
- for example attempts to work with MCP3008 fail since I need to pass data, where second unsigned byte (i.e. values 0-255) is larger than the max value of java byte (127). So to fix, use short in java (16bit signed, so it will cover unsigned byte, there could be some data loss, but at least the API would support unsigned byte values in java, i.e. > 127)
- apart from that the API is wrong. While in C and C++ I can pass around arguments and assume they would get changed from the called method, it does not work that way in java, at least not for strings for sure. For byte arrays this may work, however the current implementation does not work anyway since it only assigns the output from wiringPi to the local array in the wrapper JNI function
- so maybe ideally change the signature to rather return the array or return null if some error ocurred
- at the same time the length argument is redundant since it can be deducted from the array size (output could be different size, but that would now be the return type)

**Comment by PoJD** [comment]
I have an implementation ready in my fork, currently playing around on my raspberry to see whether it works fine wih MCP3008

**Comment by PoJD** [comment]
OK, confirmed, works fine now with my MCP3008: https://github.com/PoJD/hawa/blob/master/rpi/src/main/java/cz/pojd/rpi/sensors/spi/MCP3008Adc.java, will raise a pull request to get it to main repo too.

**Comment by PoJD** [comment]
PR here: https://github.com/Pi4J/pi4j/pull/112 (now needs some rework)

**Comment by savageautomate** [comment]
This issue should be addressed in the latest commits.  Added short[] array API method making it easier to assign values (unsigned byte) 128-255 to array elements.  Also added a new SPI interface with a more friendly Java OO API.  Commit https://github.com/Pi4J/pi4j/commit/33f46007c5514f36df163a58027ffd5482daef7e or later.

**Comment by PoJD** [comment]
Tested latest shapshot in my app and works as expected, thanks! https://github.com/PoJD/hawa/commit/b58dbcf9e3dfe38c9bf7610a009cf8213def550d

**Comment by savageautomate** [comment]
Thanks for the update!  Glad to hear its working.  I also tested on the PiFace (MCP23S17) and it seems to work there too.
