### ISSUE TITLE
State-switching at initialisation

### ISSUE THREAD

**Issue by K1LLUM1N471** [Pi4J/pi4j-v1#124]
Hello,

I'm using an addon-board with four opening relays. Everything works fine and I can switch them all correctly.
To initialise I used "relais1 = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_00, "", PinState.HIGH);"
When I run my sources a second time and the relay is already is the state HIGH, the first relay change it's state to LOW for a few milliseconds -> that is not desired!
Is this issue known and does a workaround exists?

Kind regards,
K1LLUM1N471

**Comment by savageautomate** [comment]
Issue confirmed and fixed.  I'll post a new build tonight with this fix.

**Comment by savageautomate** [comment]
Hi K1LLUM1N471 ,

Were you able to verify if the new build fixed this issue for you?

Thanks, Robert

**Comment by K1LLUM1N471** [comment]
Thank you, everything seems to work fine now. 
Yesterday I verified the functionality with an oscilloscope, too.
Kind regards,
K1LLUM1N471

**Comment by savageautomate** [comment]
Thanks for the update confirmation!
