### ISSUE TITLE
Wrong GPIO Info

### ISSUE THREAD

**Issue by metropt** [Pi4J/pi4j-v1#126]
Hi,
The GPIO image you have here http://pi4j.com/pins/model-b-plus.html is incorrect.

**Comment by savageautomate** [comment]
Can you please elaborate?  What is wrong so that we can correct it.  
Please keep in mind that the pin numbering scheme is based on the WiringPi numbering scheme and is not the raw Broadcom chip GPIO pin numbers.

**Comment by metropt** [comment]
Hmm, I don't know how wirinpi works but the GPIO from the Raspberry shecmatic is the following: http://www.element14.com/community/servlet/JiveServlet/previewBody/68203-102-6-294412/GPIO.png per example the GPIO 23 and 24 are diferent on your image compared to the original.

**Comment by savageautomate** [comment]
Yep, those are the raw broadcom chip GPIO pin numbers.  The Pi4J project uses the (abstracted) WiringPi numbering scheme.  The image below shows a mapping between the two different schemes. 

![image](https://cloud.githubusercontent.com/assets/2251458/6158759/ba7b0e30-b21b-11e4-8e97-8d240a1c79fe.png)

Thanks!
