### ISSUE TITLE
LCD library

### ISSUE THREAD

**Issue by Ropsch** [Pi4J/pi4j-v1#13]
Robert, Thanks for this great library, it is a major help for my school project!

I just got the LCD library working by porting an existing WiringPi based C test project.
However, the lcdClear() method corrupts the display every time, and occasionally I get a messed up display after writing the very first character after lcdInit().
Maybe it's a timing issue, or my display is on the borderline of its specs.

Has anyone else tried using the LCD class?

Thank you a lot, keep up the good work!

**Comment by savageautomate** [comment]
I have not had any other reports of users attempting the LCD.  What LCD device/kit are you using?  I would like to try it out first hand.  Thanks, Robert

**Comment by Ropsch** [comment]
Hello Robert,

Thanks for your reply.
I use a cheapo 16x2 digit display in 4 bit mode.
My config involves the SPI pins, but I am not aware of SPI being activated
on my system. Also the same config works fine in a C program.
The problem occurs when I use lcdClear() and lcdHome() like below. I use a
workaround by overwriting characters with spaces, which always works.

if (Gpio.wiringPiSetup () == -1) return;
lcdID = Lcd.lcdInit (2, 16, 4, 14, 6, 11, 10, 13, 12, 0, 0, 0, 0);
  if (lcdID == (-1))  return;
Lcd.lcdClear(lcdID);
Lcd.lcdHome(lcdID);
Lcd.lcdPuts (lcdID, "Hello World");

This has two possible outputs on the display, by a chance of about 50-50.
1.: "o World" - note the missing first part. After this everything works
just fine.
2.: a bunch of random weird characters.  lcdPuts() outputs random stuff
from here on.

I hope this helps somewhat.
Cheers!

2012/12/8 Robert Savage notifications@github.com

**Comment by savageautomate** [comment]
I need to acquire a LCD board to test/fix this issue.

**Comment by savageautomate** [comment]
Ordered hardware; waiting on LCD devices to arrive.

**Comment by johngamarra** [comment]
Hi, I already seen the same problem with LCDs Is this issue going to be fixed soon?

**Comment by savageautomate** [comment]
Testing this today.

**Comment by savageautomate** [comment]
OK, I tested this today using this 4-bit LCD kit:
http://mypishop.com/Read%20Your%20Pi%20!.html

All the functions seem to be working correctly for me (home, clear and puts).  I worked on the LCD implementation a few weeks back and added a Pi4J device abstraction layer as well. 

Check out these sample projects:

This sample code uses the WiringPi JNI wrapper functions:
https://github.com/Pi4J/pi4j/blob/develop/pi4j-example/src/main/java/WiringPiLcdExample.java

This sample code uses the new Pi4J LCD device abstraction:
https://github.com/Pi4J/pi4j/blob/develop/pi4j-example/src/main/java/LcdExample.java

These examples are based on the latest 0.0.5-SNAPSHOT version of Pi4J. 
Please test with the latest build and let me know if there is still a problem.

Thanks, Robert

**Comment by johngamarra** [comment]
tested this week with a 4x20 LCD in 8-bit mode using WiringPi wiring, no issues so far...

**Comment by savageautomate** [comment]
That's great news!
