### ISSUE TITLE
i2c1 write failure on sama5d4

### ISSUE THREAD

**Issue by sureshsc76** [Pi4J/pi4j-v1#134]
hello,

i'm facing i2c1 write failure error on SAMA5D4 xplained board when i execute below two i2cset command.

i2cset 1 0x5B 0x54 0x39
i2cset 1 0x5B 0x55 0x80

without turning on VDDANA analog rail needed for the GPIO hardware won't work on SAMA5D4 board. same hardware tested on SAMA5D3 and it's wroking fine.

any thought on this?

**Comment by savageautomate** [comment]
Is this Pi4J related?
