### ISSUE TITLE
Addition of JavaDoc comments

### ISSUE THREAD

**Issue by nkolban** [Pi4J/pi4j-v1#142]
Would it be possible to add more JavaDoc comments?  For example, the utils.String package doesn't contain any descriptions of the methods.

Another example is the pulse() methods.  The docs don't declare what time unit the duration is measured in.

**Comment by agausmann** [comment]
+1 for this. The documentation is severely lacking; even after browsing through the source code I haven't found the range for analog inputs. I want to assume it is a voltage level, but I can't assume anything. Units and values like these _need_ to be included so end users know how to handle the data.

**Comment by savageautomate** [comment]
I agree there is room for improvement. 

The analog input interfaces don't dictate a range or unit type.  The Pi hardware does not support any analog inputs directly, but Pi4J does support analog input when using some ADC chips via the pi4j-gpio-extensions library.

**Comment by savageautomate** [comment]
**closed**; Pi4J v2 provides much better documentation in code
