### ISSUE TITLE
Math bug for PCA9685

### ISSUE THREAD

**Issue by DataWorm** [Pi4J/pi4j-v1#153]
I used sources from current master branch on my pi with oracle java 8. When I tried to use PCA9685GpioServoDriver I received the following error:
java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.

I was able to fix this bug for me and want to provide the fixed code for `com.pi4j.component.servo.imp.PCA9685GpioServoDriver.java`:

```
protected void updateResolution() {
    resolution = new BigDecimal(4096).divide(getProvider().getFrequency(), MathContext.DECIMAL32).intValue();
}
```

**Comment by savageautomate** [comment]
Fixed in 1.1-SNAPSHOT
