### ISSUE TITLE
Need a check of real presence of several PiFace via PiRack

### ISSUE THREAD

**Issue by psytester** [Pi4J/pi4j-v1#156]
Maybe I missed the required details of how to get those infos...

In my case I have one common java code and two RPi.
1. RPi has connected only one PiFace directly on its board and address is set to 0
2. RPi has connected two PiFace via PiRack with address 0 and 1 (And maybe this RPi gets two more PiFace boards in future)

I access the PiFace via created objects:
piface1 = new PiFaceDevice(PiFace.ADDRESS_0, Spi.CHANNEL_0);
piface2 = new PiFaceDevice(PiFace.ADDRESS_1, Spi.CHANNEL_0);

For sure, this does not return <null> nor IOException in case 2. PiFace was not found as connected board.
Inside this PiFaceDevice object, I did not found any get****() method to see if the PiFace is really there.

Next step, I thought I will find a SystemInfo generic way to retrieve some details about connected Hardware, but com.pi4j.system.SystemInfo does not have it.

I need it to distinguish in my code the execution of methods based on found PiFace boards.
Something like "if piface2 is present then execute the code, else just bypass it".

If not already given and if this is possible, can you please provide such a generic board status/presence check?

**Comment by savageautomate** [comment]
Closed.  Peripheral device detection is beyond the scope of this project.
