### ISSUE TITLE
I want to control GPIO on Android platform , is there any possible ? 

### ISSUE THREAD

**Issue by wabp2005** [Pi4J/pi4j-v1#164]
I want to control GPIO on Android platform , is there any possible ?

**Comment by abhijeetramgir** [comment]
Even I want to know,
Anybody?

**Comment by ghost** [comment]
Android is Linux. If you have a rooted device with GPIO you can follow the Raspberry PI GPIO example from Oracle and write to the file handler itself, directly. There is no need for PI4J to do this as Linux is a Un*x system and everything has a file handler. You just need to know where it is and if you have permission.

--jb

Sent from Yahoo Mail on Android

**Comment by savageautomate** [comment]
Pi4J itself just allows your Java code to communicate with the hardware.  You have to add your own code to expose it over the network.

However, last year I gave a talk at Devoxx where I demonstrated using Pi4J and a Raspberry Pi to communicate sensor data via MQTT over the network to both a JavaFx application and an Android app on a mobile device. 

Check out this page for the slides and links:
http://www.savagehomeautomation.com/devoxx

The following projects are the ones I am talking about.
- Pi4J Home Automation Sensors Demo using MQTT (Source Code + NetBeans Project)
- Pi4J Home Automation Sensors Demo using MQTT on Android (Source Code + Android Studio Project)
