### ISSUE TITLE
Serial Pi4J not working on RPI2

### ISSUE THREAD

**Issue by ecmnet** [Pi4J/pi4j-v1#165]
It seems to me, that the serial PI4J is not working on RPI2. I followed the instructions on http://www.irrational.net/2012/04/19/using-the-raspberry-pis-serial-port/. The serial port still cannot
be found. purejavacomm however works fine.

**Comment by savageautomate** [comment]
I tested the serial communication using Pi4J today on the latest Raspbian image (2015-05-05-raspbian-wheezy.img) and its all seems to be working fine on my RPi2B.

I tested using Pi4J Version 1.0.  Passed.
I tested using Pi4J Version 1.0.1-SNAPSHOT.  Passed.
I tested using Pi4J Version 1.1-SNAPSHOT.  Passed.

Make sure you run `sudo raspi-config` and select `Advanced Options`, `A8 Serial`, and select `No` to disable the shell/console from using the serial port and reboot to apply the setting.

I tested using the SerialExample code included in the Pi4J project:

[1.0 & 1.0.1-SNAPSHOT] https://github.com/Pi4J/pi4j/blob/master/pi4j-example/src/main/java/SerialExample.java  

[1.1-SNAPSHOT] https://github.com/Pi4J/pi4j/blob/develop/pi4j-example/src/main/java/SerialExample.java
