### ISSUE TITLE
Pins 4 to 7 in MCP3008Pin class appear to refer only to pin 4.

### ISSUE THREAD

**Issue by igoralves98** [Pi4J/pi4j-v1#166]
![pins](https://cloud.githubusercontent.com/assets/12055297/8763123/6a78f882-2d65-11e5-8bc0-a996b16be70a.jpg)
I'm doing a project that uses an MCP3008 to read some analogue data.

By the way the classes MCP3008GpioProvider and MCP3008Pin are awesome and easy to work.

But, unfortunately it seems that class MCP3008Pin has a address problem: when I try to read the voltages from all the eight pins, pins 4 to 7 have the same value.

**Comment by savageautomate** [comment]
Thanks for the fix.  Merged into master branch.
