### ISSUE TITLE
Using this Pi4J to develop RFID system.

### ISSUE THREAD

**Issue by rhonyabdullah** [Pi4J/pi4j-v1#168]
Sorry, this may sound like a dumb question but can i use this Pi4J to develop RFID system ? I'm new in hardware programming. Thanks

**Comment by savageautomate** [comment]
I think the answer is yes.  Pi4J does not implement any RFID specific code, but if you have an RFID reader that can communicate via TTL (serial), I2C, or SPI, then you could use Pi4J to communicate with the reader.  Pi4J would just act as your communications interface to the RFID reader.

I have not use any of these hardware interfaces, but just included them as examples:

SPI communication to RFID reader:
http://store.linksprite.com/rfid-reader-write-module-spi-interface/

Serial communication to RFID reader:
http://www.rhydolabz.com/index.php?main_page=product_info&products_id=476

I2C communication to RFID reader:
http://skpang.co.uk/catalog/hf-rfid-module-sl030-33v-i2c-p-1065.html

serial or I2C:
https://www.sparkfun.com/products/10126
