### ISSUE TITLE
Add Java API for SPI communications

### ISSUE THREAD

**Issue by savageautomate** [Pi4J/pi4j-v1#18]
Add a Java-friendly API for SPI communications.

**Comment by savageautomate** [comment]
re-opening, accidental closure

**Comment by Dan-83** [comment]
Hey guys,

Loving your work so far, I'm using p4j to connect my pi up to some motors and creating a little toy car. It's pretty primitive right now and will travel in wobbly lines on un even surfaces etc, so I want to connect up a gyroscope and correct the direction by temporarily turning off one of the motors.

The gist is that I need to use SPI to talk with the gyro, and will eventually probably need to get better motors that also use SPI. Do you have a time frame on the development for SPI?

Cheers

Dan

**Comment by savageautomate** [comment]
Hi Dan,

I don't have any concrete dates for further SPI development.  I actually need to order some SPI controlled devices to develop around a few concrete use cases and have physical equipment to test with.  

However there is existing support in the project for basic SPI communications.  Since Pi4J provides a direct wrapper around the native WiringPi project, we do provide an SPI static utility class that provides access to SPI.  Check out this class:  http://pi4j.com/apidocs/index.html?com/pi4j/wiringpi/Spi.html 
and the native implementation:  
https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPiSPI.c

Our plans in Pi4J would be to create a more Java-friendly API on top of the native impl, but for now you should be able to just use the wiringPi wrapper interface. 

Thanks, Robert

**Comment by Dan-83** [comment]
Thanks!

**Comment by rlsutton1** [comment]
I'm quite impressed with pi4j and would love to contribute when I get a bit more familiar with the lib and my very shiny new pi.

For when you get around to implementing it... I've been using the Spi class, I currently see a significant issue with the exposed method Spi.wiringPiSPIDataRW in that it takes a string as the data to send. 

The device I'm using needs to receive binary data, converting a byte array to a string doesn't really work in java - unicode and all. Also I don't think too many devices will take kindly to receiving unicode strings.

**Comment by rlsutton1** [comment]
After much testing, the unicode issue is a big problem - a single byte becomes 1 or more bytes depending on the value. I've tried various encoding techniques to get around this without any luck. Also it's not possible to pass 0's as they are either being omitted or are terminating the string (not sure which).

**Comment by savageautomate** [comment]
It seems like we could sort out the string encoding and maybe provide a byte array method argument in an overloaded function (instead of a string parameter).

**Comment by savageautomate** [comment]
@rlsutton1 

I have created a separate ticket for the issue you noted:  https://github.com/Pi4J/pi4j/issues/29

Thanks, Robert

**Comment by PoJD** [comment]
Look also at my change: https://github.com/PoJD/pi4j/commit/d2a02fc97db0e3667119377eda9fe752f930decd part of pull request #112 and fixes issue #111. It uses short[] for input and output too. I also suggested more OOP friendly API in there inside #112, am happy to get it in, or potentially in my private fork.

**Comment by savageautomate** [comment]
Included new SPI OO interface as of commit https://github.com/Pi4J/pi4j/commit/0a28c277692c96be4c903a836d398f129be18c32 and later.

See interfaces here:
https://github.com/Pi4J/pi4j/tree/develop/pi4j-core/src/main/java/com/pi4j/io/spi

And updated PiFace impl that consumes the new SPI interface here:
https://github.com/Pi4J/pi4j/commit/0a28c277692c96be4c903a836d398f129be18c32

Closed issue.
