### ISSUE TITLE
GpioCallbackTrigger

### ISSUE THREAD

**Issue by SageDesign** [Pi4J/pi4j-v1#184]
The third example in the pi4j set includes a Gpio Callback, but it will ot compile. I have found other examples which show the same code, but cannot find anything wrong with my typing - it appears to be correct, but the compiler does not like "new Callable<Void>()".
The import appears to be correct, but something is wrong which I cannot see. Help would be most appreciated.

**Comment by savageautomate** [comment]
Which version of Java JDK are you attempting to compile with?  
Thanks, Robert

**Comment by savageautomate** [comment]
no update, closing issue
