### ISSUE TITLE
NATIVE (WIRINGpIisr) ERROR; JNI 'CallbackWrapperFunc' could not get 'callback' method id.

### ISSUE THREAD

**Issue by proul** [Pi4J/pi4j-v1#194]
When I run the code WiringPiGpioInterruptExample2.java, press the button, there are the following error tips, how should we solve? Thank you

NATIVE (WIRINGpIisr) ERROR; JNI 'CallbackWrapperFunc' could not get 'callback' method id.
NATIVE (WIRINGpIisr) ERROR; JNI 'CallbackWrapperFunc' could not get 'callback' method id.

**Comment by savageautomate** [comment]
Are you using the latest 1.1-SNAPSHOT builds?  I remember a similar issue that should have been resolved/fixed in the latest builds. 

Thanks, Robert
