### ISSUE TITLE
Parity/framing error with DataBits._7

### ISSUE THREAD

**Issue by inaanpo** [Pi4J/pi4j-v1#195]
Hi,
(Snapshot 1.1). I get parity/framing error when i use DataBits_7. OK with DataBits_8.
 serial.open("/dev/ttyUSB0", Baud._9600, DataBits._7,
                        Parity.EVEN, StopBits._1, FlowControl.NONE);

**Comment by savageautomate** [comment]
Related Bug: https://github.com/Pi4J/pi4j/issues/135

A new 1.1-SNAPSHOT build is now available that attempts to fix this issue.

**Comment by savageautomate** [comment]
Fixed in 1.1-SNAPSHOT.
