### ISSUE TITLE
Questions about ADS1115

### ISSUE THREAD

**Issue by proul** [Pi4J/pi4j-v1#210]
A0-A3 seems to have reversed.
A0=>A3
A1=>A2
A2=>A1
A3=>A0

Provides a demo of a single ended input,,How to use differential input in the program?

thanks

**Comment by savageautomate** [comment]
I tested this today using this Adafruit module: https://www.adafruit.com/product/1085
All inputs (A0 to A3) reported the correct voltages as I applied power to each pin individually.   

Differential input is not currently supported in the implementation code.
