### ISSUE TITLE
Gpio.wiringPiISR() causing crash of Java Runtime Environment 

### ISSUE THREAD

**Issue by HapibotDinis** [Pi4J/pi4j-v1#214]
I'm using 1.1-SNAPSHOT build and the application crashes when receiving an interruption defined as the one below:

Gpio.wiringPiISR(MIC_PIN, Gpio.INT_EDGE_FALLING,new GpioInterruptCallback() {
    ... 
});

This error has been reported in previous issues (#180, #176, #182) and the solution was to use the latest snapshot, which I did.
I've attached an error log.
Any solution will be appreciated. Thank you.
[hs_err_pid2976.txt](https://github.com/Pi4J/pi4j/files/101022/hs_err_pid2976.txt)

**Comment by savageautomate** [comment]
I am actively looking into this issue.  I did not experience a crash, but its was not working properly either.  Looking deeper into the issue tomorrow.  Thx!

**Comment by savageautomate** [comment]
I have attempted to fix this issue.  It seem to be working for me now.  Please try and reopen the issue if you still see a problem.   Thanks, Robert
