### ISSUE TITLE
ads1115 example code

### ISSUE THREAD

**Issue by simondid** [Pi4J/pi4j-v1#219]
hey

so i been playing around with the ads1115 example code and goth it working but for some reason it seems like the 4 inputs one the adc dos not register right example chaing the value on a2 might register as change on a3 and a0 as a1 and a3 as a0 and and a1 as a2 i trayed the wire setup on and arduino with some diffrent code with work no problem i can't locate the error but pleas take a look at it :P 

my bad it seems the ads1115 bord i have some kinde wired error

**Comment by savageautomate** [comment]
I tested this today using this Adafruit module: https://www.adafruit.com/product/1085
All inputs (A0 to A3) reported the correct voltages as I applied power to each pin individually.   

Make sure to apply a GROUND to the analog input pins that you are not using.  If you don't ground them they will float and report erroneous values.
