### ISSUE TITLE
RejectedExecutionException error

### ISSUE THREAD

**Issue by jasonkaisersmith** [Pi4J/pi4j-v1#220]
I have a test class that listens for a button to be pressed and then does something.  The class is part of many in a larger program and it is possible that it is created and run multiple times.

On the first execution I have no problem, but when executing a second (or more) times then I'm getting an "RejectedExecutionException" error.  

Full stack trace

> Exception in thread "Thread-14" java.util.concurrent.RejectedExecutionException: Task com.pi4j.io.gpio.tasks.impl.GpioEventDispatchTaskImpl@11f409d rejected from java.util.concurrent.ThreadPoolExecutor@1d8bcce[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12]
>         at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
>         at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
>         at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
>         at com.pi4j.concurrent.ShutdownDisabledExecutorWrapper.execute(ShutdownDisabledExecutorWrapper.java:113)
>         at com.pi4j.io.gpio.impl.GpioEventMonitorExecutorImpl.handlePinEvent(GpioEventMonitorExecutorImpl.java:91)
>         at com.pi4j.io.gpio.GpioProviderBase.dispatchPinDigitalStateChangeEvent(GpioProviderBase.java:332)
>         at com.pi4j.io.gpio.RaspiGpioProvider.pinStateChange(RaspiGpioProvider.java:206)
>         at com.pi4j.wiringpi.GpioInterrupt.pinStateChangeCallback(GpioInterrupt.java:126)

Now to me it seems like something is not being shutdown properly, but I can't find what it is!

My code is as follows;

Constructor

```
GpioPinDigitalInput buttonPin;


this.buttonPin = gpio.provisionDigitalInputPin(RaspiPin.GPIO_03, PinPullResistance.PULL_DOWN);      
this.buttonPin.setShutdownOptions(true, PinState.LOW);  
this.buttonPin.addListener(this);
```

Shutdown

```
this.buttonPin.removeAllListeners();
gpio.unprovisionPin(buttonPin);
this.gpio.shutdown();
```

Any ideas?

**Comment by savageautomate** [comment]
When you say ...

>  it is possible that it is created and run multiple times.

Do you mean the class gets instantiated and destroyed multiple times in a continuously running process?  
Or does the entire process get shutdown and re-launched/started from some external parentprogram?  

If the entire program/process is not terminating, then you probably should not use the `this.gpio.shutdown();` call.  You should be able to provision and un-provision pins just fine as often as needed in a process.  `this.gpio.shutdown();`  is really for when you are completely terminating your application/process.  It will do things like un-export the GPIO pin and set it to a default shutdown state.

Thanks, Robert
