### ISSUE TITLE
50ms interval in com.pi4j.gpio.extension.ads implementations

### ISSUE THREAD

**Issue by wnagele** [Pi4J/pi4j-v1#223]
Is there a good reason why the monitorInterval can not be set lower than 50ms? In reality that doesn't even allow to get close to the sample rates these devices could provide.

**Comment by savageautomate** [comment]
I think it was originally put in place to prevent the polling effort from consuming too much of the system resources.  However, with the newer hardware and improved performance, this may be less of a concern these days.  I'm happy to reduce the lower limit.  (Maybe to 1ms?)

**Comment by savageautomate** [comment]
Now supports interval down to 1 ms.  Use low interval values at your own risk :-)

**Comment by savageautomate** [comment]
new 1.1-SNAPSHOT build posted with these changes.
