### ISSUE TITLE
Add support for Raspberry Pi Zero

### ISSUE THREAD

**Issue by savageautomate** [Pi4J/pi4j-v1#227]
## Issue

Officially add support for Raspberry Pi Zero
## Progress

The following steps need to be completed to officially announce support for the Pi Zero.
- [X] update wiringPi to latest version
- [X] test/validate GPIO outputs
- [X] test/validate GPIO inputs with pull down
- [X] test/validate GPIO inputs with pull up
- [X] test/validate serial communication
- [X] test/validate  I2C communication
- [X] test/validate  SPI communication
- [X] update project readme
- [x] update project documentation
## Summary

With the latest builds of 1.1-SNAPSHOT, Pi4J is fully functional and tested with the RaspberryPi Zero.  All that remains is publishing updated documentation.  The pin numbering scheme for the Zero is exactly the same as the 2B and listed here: http://pi4j.com/pins/model-2b-rev1.html
## Known Issues

None.

**Comment by truell20** [comment]
What is the update on this? I would like to use Pi4J on the Rasberry Pi Zero. Is implemented and tested?

**Comment by savageautomate** [comment]
Yes, it is implemented and tested on the latest 1.1-SNPSHOT builds.  
Documentation still needs to be updated.

**Comment by savageautomate** [comment]
Updated site docs for Raspberry Pi Zero (v1.1) release.
