### ISSUE TITLE
Add Support for Chip (getchip.com)

### ISSUE THREAD

**Issue by hkuhn42** [Pi4J/pi4j-v1#236]
Would be nice to have support for http://getchip.com/pages/chip.

**Comment by savageautomate** [comment]
I agree :-)

First we need a WiringPi port for Chip.  

I see a comment on that in this thread, but was not able to locate a WiringPi project for Chip.  
https://bbs.nextthing.co/t/turning-the-chip-into-an-amazon-echo/1630

Thanks, Robert

**Comment by simondid** [comment]
any updates on this ??

and will we need to be running raspbian ore c.h.i.p os ore dos this not matter?

**Comment by simondid** [comment]
this might be interesting to whoever is trying to implement support for c.h.i.p

https://bbs.nextthing.co/t/wiring-chip-building-a-wiring-pi-c-interface-for-chip/7918/8

**Comment by savageautomate** [comment]
closed
