### ISSUE TITLE
Require root for pi3

### ISSUE THREAD

**Issue by edwardcapriolo** [Pi4J/pi4j-v1#238]
For the PI3 it seems like pi4j requires root, but python apps do not have this limitation. If do not mind pitching in the fix

**Comment by savageautomate** [comment]
@edwardcapriolo 

Pi4J _should_ already work without root access.  See this post:
http://www.savagehomeautomation.com/projects/pi4j-now-supports-non-privileged-access-no-more-rootsudo.html

Please let me know if its not working for some reason :-)

PS. certain features such as hardware PWM control still require root access.  Basic GPIO usage no longer requires root access.  But here are a few things need to configure your system and application first.

Thanks, Robert

**Comment by edwardcapriolo** [comment]
Can you re-open. The problem is this code you mention is only in your unpublished-to maven branch. When are you planning on publishing this release to central? It is impossible to release downstream code with a snap-shot dependency.

**Comment by savageautomate** [comment]
The SNAPSHOT builds are published to a Maven repository, just not Maven Central:
http://pi4j.com/download.html#Source_Repository

I am working to get the release wrapped up in the next week or two.

**Comment by edwardcapriolo** [comment]
I understand about the SNAPSHOT, but the problem is you can not release a project that has a snapshot dep. It is also confusing for users that blogs written almost a year ago have code features not released yet.

**Comment by savageautomate** [comment]
I understand :-)   And I agree that its been way too long without a release build. 
Working on final items to release very soon.

Thanks, Robert
