### ISSUE TITLE
Using Pi4J with an ESC & a brushless motor

### ISSUE THREAD

**Issue by DarkmatterVale** [Pi4J/pi4j-v1#254]
Is it possible to use Pi4J to initialize an ESC & then run a brushless motor?

More specifically, can I use Pi4J to run a WP-1040 Brushed (Crawler) ESC with a brushless DC motor (http://www.hobbyking.com/hobbyking/store/__26267__133RPM_Brushed_Motor_w_75_1_Gearbox.html)? If so, how would I go about accomplishing that? Any help would be appreciated.

Thank you for the help in advance!

**Comment by pasha-shestakov** [comment]
Im just curious, but looks like your building an RC car? (well is guess it probably not remote controlled :)) If not a secret, may i ask what for?

**Comment by natdan** [comment]
Yes.

Please refer to: https://www.raspberrypi.org/forums/viewtopic.php?f=81&t=154475&sid=cbda77bf4971b15cf735c0ab51682d19

If driven directly from RPi you can use servoblaster driver (https://github.com/richardghirst/PiBits/tree/master/ServoBlaster). Example is here: https://github.com/Pi4J/pi4j/blob/master/pi4j-example/src/main/java/RPIServoBlasterExample.java

It should be straightforward.

**Comment by natdan** [comment]
@pasha-shestakov  while you are waiting for @DarkmatterVale 's answer - I can give you another: I'll be building a robot with a school's club soon (immediately after summer) and it will hopefully be using similar setup: brushed/brushless car ESC with servoblaster, pi4j, etc... And it _will_ be remotely controlled (serial over bluetooth or socket over WiFi from Android phone/web interface).

**Comment by savageautomate** [comment]
Questions/conversation should move to the Pi4J forums you may get a larger audience to help.  https://groups.google.com/forum/#!forum/pi4j

Closing this issue.  Thanks, Robert
