### ISSUE TITLE
New Serial JNI interface does not allow baudrates above 230400 ?

### ISSUE THREAD

**Issue by florian-z** [Pi4J/pi4j-v1#257]
With the old serial interface (by using .open() directly) it is possible to use baudrates above 230400, e.g.:

```
int baudrate = 1000000;
final Serial serial = SerialFactory.createInstance();
serial.open(Serial.DEFAULT_COM_PORT, baudRate);
```

But I cannot find a way to do this with the new serial interface (using .baud() to set the baudrate).

```
SerialConfig config = new SerialConfig();
config.device(SerialPort.getDefaultPort())
    .baud(Baud._230400)
    .dataBits(DataBits._8)
    .parity(Parity.NONE)
    .stopBits(StopBits._1)
    .flowControl(FlowControl.NONE);
// config.baud(Baud.getInstance(1000000));    // causes null pointer
serial.open(config);
```

Is this on purpose?

**Comment by savageautomate** [comment]
You  an still use the Serial.open() method to pass a custom baud rate as an integer.
https://github.com/Pi4J/pi4j/blob/master/pi4j-core/src/main/java/com/pi4j/io/serial/Serial.java#L102

The SerialConfig object is just an optional convenience using the included enums. 

Thanks, Robert

**Comment by florian-z** [comment]
Okay, great.
