### ISSUE TITLE
error: Cannot find symbol Baud._115200

### ISSUE THREAD

**Issue by SgtBurned** [Pi4J/pi4j-v1#263]
Whilst using the Serial section of Pi4j, Trying to set the Baud rate on a SerialConfig object using:

``` java
    SerialConfig config = new SerialConfig();
    config.device("/dev/ttyAMA0");
        .baud(Baud._115200)
        .dataBits(DataBits.8)
        .parity(Parity.NONE)
        .stopBits(StopBits._1)
        .flowControl(FlowControl.NONE);
```

Returns an error "error: cannot find symbol Baud._115200" Yet if I use the example code and change the baud it works.
I'm using the Library Java Swing for GUI. Other than that there is no difference from the Example Code.

**Comment by savageautomate** [comment]
Make sure your imports include the `Baud` enumeration class specifically or you include all classes in the serial namespace:

`import com.pi4j.io.serial.*;`

I'm not sure what else it might be?
