### ISSUE TITLE
Gpio02 problem

### ISSUE THREAD

**Issue by gkunzel** [Pi4J/pi4j-v1#27]
Hi, 

I'm using Pi4J version 0.0.4 and I have identified a possible conflict involving the Pi4J's Gpio2 pin (13th pin of the header connector). 

I tried use it as output  on my RPi but it didn't changed the logic level from 0V to 3.3V. The other gpios are working properly.

On the internet (http://elinux.org/RPi_Low-level_peripherals) I saw that in Rpi rev. 1, the 13th pin of the connector is the GPIO21, while on RPi rev.2, the same 13th pin is the GPIO27. Maybe this change on the board is affecting the use of the gpio2. My RPi board is the new one (model B, 512MB).

Maybe my board has a problem, but I think that you guys might take a look on this. 

Thank you, 
Gustavo

**Comment by savageautomate** [comment]
Please try version 0.0.5-SNAPSHOT.
I believe this has been fixed.

**Comment by savageautomate** [comment]
Well bad news maybe ... I just tested it using 0.0.4 and this GPIO pin is working correctly on my 512 Pi.  
Make sure you perform the latest software/firmware upgrade just to be sure.

sudo apt-get update
sudo apt-get upgrade

**Comment by gkunzel** [comment]
I did the update/upgrade that you suggested and now it is working properly. Thank you.
