### ISSUE TITLE
 java.lang.RuntimeException: Unable to open GPIO direction interface for pin [1]: No such file or directory

### ISSUE THREAD

**Issue by samielhini** [Pi4J/pi4j-v1#270]
This seems to happen only when trying to use RaspiPin.GPIO_01.  I have confirmed I do not have lirc installed.  Other pins work perfectly.  I am using an Ada Fruit 1.8" TFT: https://www.adafruit.com/product/358.

I'm not sure if something about the kernel drivers is causing an issue here.  It should be noted that WiringPi's GPIO command does not have an issue with writing to GPIO_01.

**Comment by savageautomate** [comment]
Just tested this today and seems GPIO_01 seems to be working properly on my RPI 3B using Pi4J v1.1.    Where you able to get this issue resolved?  Thanks, Robert
