### ISSUE TITLE
event.length() == 0 ????????

### ISSUE THREAD

**Issue by DoctorDooom** [Pi4J/pi4j-v1#272]
if event.length() == 0 why the event accured ????

Imust do the following 
if(event.length() != 0){
// do something
}
else 
    return ;

**Comment by savageautomate** [comment]
Which event?  Serial , GPIO?

**Comment by DoctorDooom** [comment]
DatalistnerEvent

**Comment by DoctorDooom** [comment]
SerialDataEvent

**Comment by aleksandrmozgovoi** [comment]
I also have this problem on SerialDataEvent.
I noticed this problem on ttyUSB0.
There are no problems with ttyUSB1 or ttyUSB2.
I'm sure that this one comes in 22 bytes, but length = 0.
How to fix it?
Sometimes for a while the reboot helps, but this is not a solution.
