### ISSUE TITLE
DebounceGpioExample not working. Debounce functions not found.

### ISSUE THREAD

**Issue by JuhaMcEla** [Pi4J/pi4j-v1#273]
I'm trying to run`DebounceGpioExample.java` but compiler don't found xxxDebounce() functions.

So compiler gives the error:
`Exception in thread "main" java.lang.RuntimeException: Uncompilabe source code - Erroneous sum type: com.pi4j.io.gpio.GpioPinDigitalInput.setDebounce at debounce.DeBounce.main (DeBounce.java:49)`

I'm using pi4j-core.jar version 1.1

**Comment by savageautomate** [comment]
I just tried this on a RPi v3 and it worked here ...

What do you get if you enter command `pi4j --version` on the command line?

If an older version of Pi4J is installed, it could be picking up the older version JARs in the classpath.

Thanks, Robert

**Comment by JuhaMcEla** [comment]
I get `command not` found when using `pi4j --version` -command. I tried also remove downloaded `pi4j-core.jar` from dir which I add to classpath with java -cp -command and compiler gave `NoClassDefFoundError: com/pi4j/io/gpio/GpioFactory` so I think compiler didn't use any other pi4j-version?

Is there any version-method in pi4j-library that I could use to verify my pi4j-version used?

BTW...I'm using RPi v1 Model B+

Thank you.

**Comment by savageautomate** [comment]
Sorry for the delay.  Were you able to get past this issue?

**Comment by savageautomate** [comment]
**Closed.**  No further activity.
