### ISSUE TITLE
cant find /sys/devices/platform/sunxi-i2c.0

### ISSUE THREAD

**Issue by cjdg** [Pi4J/pi4j-v1#282]
Hi i tried examples for banana pi and i get the following error, im using bananian 8.6 and the banana 1

exception in thread "main" java.io.FileNotFoundException: /sys/devices/platform/sunxi-i2c.0/i2c-0/0-0034/temp1_input

**Comment by savageautomate** [comment]
Is it the LeMaker BananaPi ?  Or another manufacturer?

**Comment by cjdg** [comment]
Lemaker bpi 1

**Comment by savageautomate** [comment]
Banana Pi Zero is no longer supported in Pi4J v1.4. 
For more details, please see:
 - https://pi4j.com/1.4/index.html
 - https://github.com/Pi4J/pi4j/blob/master/README.md
