### ISSUE TITLE
is pi4j safe to deal with multiple Rs485 interfaces????

### ISSUE THREAD

**Issue by DoctorDooom** [Pi4J/pi4j-v1#283]
Hello All
I want to ask if pi4j safe to deal with multiple Rs485 interfaces and what is the bes to to deal with this status ??? there are two Options 
1- make one Serial Object and one listener for all interfaces but in this case the listener cache the previos data and make wrong output
2- make four Serial Object and four listener for four interfaces  ????

Please help me

**Comment by savageautomate** [comment]
Are you using a USB to RS485 adapter?  Or some other circuitry to physically connect to a 485 bus? 

I would assume you would have to create a serial object for each physical RS485 connection to the RPi.  If you are communicating with multiple devices on the 485 bus, I assume you would have to deal with the communication details to each device in the data payloads and a single listener interface where all data received by the RPi would have to be parsed.
