### ISSUE TITLE
3wire SPI (bidirectional mode) support for RPi 3

### ISSUE THREAD

**Issue by ghost** [Pi4J/pi4j-v1#339]
As mentioned [here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md) RPi3 has 3wire SPI support. Is it possible to implement it in PI4J?

**Comment by savageautomate** [comment]
At the moment the SPI implementation in Pi4J is based on WiringPi's SPI API.  

This thread suggests that the 3-wire needs some special configuration set for the spidev device.
https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=132426
```
ioctl(fd, SPI_IOC_RD_MODE32, 0x10); //enable 3wire mode
```
I looked at the WiringPi SPI implementation code and did not readily see any support for configuring this with the existing API.   
https://github.com/Pi4J/wiringPi/blob/master/wiringPi/wiringPiSPI.c

So we have to wait until WiringPi supports it or port Pi4J's SPI impl to use spidev directly in the native library.  So yes .. its possible, just not simple or quick to get done :-) 

Thanks, Robert

**Comment by savageautomate** [comment]
No further activity; issue closed.
