### ISSUE TITLE
Artifact com.pi4j:pi4j-native:0.0.4:soft-float:so is missing from Maven repository

### ISSUE THREAD

**Issue by pskopek** [Pi4J/pi4j-v1#34]
I can see only pi4j-native hard-float library in https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-native/0.0.4/.
Can you check why soft-float is missing, please?

**Comment by savageautomate** [comment]
Known issue and fixed in 0.0.5-SNAPSHOT builds.

See this thread for more details:
https://groups.google.com/forum/?fromgroups=#!topic/pi4j/3A_AijXbdsI
