### ISSUE TITLE
How to change stepper motor's speed and direction

### ISSUE THREAD

**Issue by Koolkum** [Pi4J/pi4j-v1#344]
A big and warm Hello from Shymkent! I started the stepper motor as You shown in the lesson "How to run the stepper motor". Now I want to try to use a Raspberry Pi3 in order to control the speed and direction of stepper motor via buttons. For example, when you activate a button by using the Check Box the stepper motor should start , when the cursor is on the button the engine should start with one speed, when you press the button the engine should to change speed or direction. In this task I have tried to use different ways to find the solutions,inncluding threads, but threads do not allow to reuse the GPIO, as in Java rules there is no possibility to completely disable the threads, it is possible only to suspend it, or wait until the code flow will be implemented. I wonder how it is possible to interrupt the movement of the stepper motor or to set for the stepper motor different speed or directions by pressing a button on the Raspberry Pi3. I will be gratefull to You, if Your give some instructive advices and simple code. I use the same stepper motor and driver in Your lesson about running with the stepper motor.
Kind regards, Vladimir.

**Comment by savageautomate** [comment]
The Motor interface does include stop(), forward(), reverse() and setState() methods to control the motor state. 
See: https://github.com/Pi4J/pi4j/blob/master/pi4j-device/src/main/java/com/pi4j/component/motor/Motor.java

```
public interface Motor extends Component {

    void forward();
    void forward(long milleseconds);
    void reverse();
    void reverse(long milleseconds);
    void stop();
    MotorState getState();
    void setState(MotorState state);
    boolean isState(MotorState state);
    boolean isStopped();

}
```

For speed you would have to change the step sequencing or the step interval.
See: https://github.com/Pi4J/pi4j/blob/master/pi4j-device/src/main/java/com/pi4j/component/motor/StepperMotor.java

```
public interface StepperMotor extends Motor {

    float getStepsPerRevolution();
    void setStepsPerRevolution(int steps);
    void setStepInterval(long milliseconds);
    void setStepInterval(long milliseconds, int nanoseconds);
    void setStepSequence(byte[] sequence);
    byte[] getStepSequence();
    void rotate(double revolutions);
    void step(long steps);
}
```

The step interval defines the delay time between each step controlled by the internal motor control driver thread.

Thanks, Robert
