### ISSUE TITLE
Manifest should not include OSGi ImportPackage

### ISSUE THREAD

**Issue by BryanHunt** [Pi4J/pi4j-v1#351]
I'm trying to use pi4j-core 1.2.0-SNAPSHOT in an OSGi environment and it is not working.  The Felix runtime complains that the packages imported by the bundle cannot be found.  The problem is the ImportPackage declares that the bundle imports the same packages it exports.  The fix is to simply remove the entire ImportPackage declaration.

**Comment by savageautomate** [comment]
Done. https://github.com/Pi4J/pi4j/commit/2e9dce684a2625fa4b1c02c608ebdab2939a39a6

Its was trickier than just removing an <ImportPackage> declaration.  I actually had to add an <ImportPackage> declaration that described the packages that I wanted to explicitly exclude.

So now we end up with just this in the <ImportPackage> declaration generated in the OSGI bundle manifest.     
  
```
Import-Package: javax.net.ssl,sun.misc
```

I'll have a new 1.2-SNAPSHOT build with this change uploaded in about 15 minutes.
Please let me know if this works for you.

Thanks, Robert
