### ISSUE TITLE
Unable to determine hardware version. I see: Hardware: BCM2835

### ISSUE THREAD

**Issue by mbyshiri** [Pi4J/pi4j-v1#357]
When I use the new Raspbian edtion the Java program throw the exception "Unable to determine hardware version. I see: Hardware	: BCM2835", The detail is 
 "Unable to determine hardware version. I see: Hardware	: BCM2835
,
 - expecting BCM2708 or BCM2709.
If this is a genuine Raspberry Pi then please report this
to projects@drogon.net. If this is not a Raspberry Pi then you
are on your own as wiringPi is designed to support the
Raspberry Pi ONLY.
"
My device is Raspberry Pi 3B

**Comment by mbyshiri** [comment]
I use Raspberry Pi 3B

**Comment by ribasco** [comment]
You need to upgrade to 1.2 snapshot. See https://github.com/Pi4J/pi4j/issues/349

**Comment by savageautomate** [comment]
closed, duplicate #349
