### ISSUE TITLE
Extend Servo abstractions to support turning off the servo (no pulses)

### ISSUE THREAD

**Issue by salk31** [Pi4J/pi4j-v1#363]
ServoBlaster at least supports this but I can't see how the Servo interface exposes this ability.

I'm up for trying to create a patch if not a silly idea?

NB I'd be tempted to mark ValidationException as deprecated as only seems to be used be the servo code. I'll listen out for screams.

Cheers

Sam

**Comment by natdan** [comment]
Great idea. Go for it! :)

**Comment by salk31** [comment]
Leaning towards off() (copying the Power interface)... With the implementations I can't test just throwing UnsupportedOperationException until somebody wants to add an implementation.

**Comment by salk31** [comment]
Using ServoBlaster I'm getting glitches. Maybe in some cases an already started pulse gets shortened?

**Comment by salk31** [comment]
Thanks
