### ISSUE TITLE
RPi Zero W "Unsupported/unknown board type; unable to detect hardware."

### ISSUE THREAD

**Issue by youcangetme** [Pi4J/pi4j-v1#366]
I just got my little Zero W v1.1 and it does not run the example code. I get the following error;

`Error creating bean with name 'serialExample': Invocation of init method failed; nested exception is com.pi4j.io.gpio.exception.UnsupportedBoardType: Unsupported/unknown board type; unable to detect hardware.`

Not sure why it has to hit the GPIO to talk on a USB serial port but that point is mute when it doesn't recognize the hardware anyways.

**Comment by savageautomate** [comment]
Are you using it with Pi4J 1.2-SNAPSHOT ?  It should work with the latest snapshots?

**Comment by youcangetme** [comment]
Moved on to better supported products...
