### ISSUE TITLE
GpioPinDigital IO setup by example

### ISSUE THREAD

**Issue by zharvey-welltok** [Pi4J/pi4j-v1#370]
First time using a Raspberry Pi, let alone pi4j, and I have a fairly simple use case where I will have 3 types of devices connected to my GPIO pins:

1. LEDs
2. Switches
3. Buzzers

I just wanted to confirm that I'm using the pi4j API correctly for each type of device:

### LEDs & Buzzers
I assume LEDs and Buzzers are both considered *output devices* (you send them a signal and they light up or make sound), and so I *believe* I want to set them up as output pins like so:

```
GpioController gpioController = GpioFactory.getInstance();
GpioPinDigitalInput myLed = gpioController.provisionDigitalOutputPin(RaspiPin.GPIO_01,
    'MyLed', PinState.LOW);
GpioPinDigitalInput myBuzzer = gpioController.provisionDigitalOutputPin(RaspiPin.GPIO_03,
    'MyBuzzer', PinState.LOW);
```

### Switches
I assume Switches are *input devices* and as such need to set them up like so:

```
GpioController gpioController = GpioFactory.getInstance();

// Set it low at startup and then allow the switch to send a HIGH signal if it is pressed.
GpioPinDigitalOutput mySwitch = gpioController.provisionDigitalInputPin(RaspiPin.GPIO_04,
    'MySwitch', PinState.LOW);
```

**My question:** Am I understanding the API & problem model correctly? Anything I need to add/change (in order to set the pins up correctly and send signals to them or check their state) beyond what I have?

**Comment by savageautomate** [comment]
I realize this is an old issue and the response is probably of no value to you at this point, but adding it in case it helps someone else in the future.

---
**Yes.**  What you have defined looks mostly correct. 
The only thing I see wrong is the input pin provisioning.  The example below should properly accomplish the goal.
```java
// Set it low at startup and then allow the switch to send a HIGH signal if it is pressed.
GpioPinDigitalInput mySwitch = gpioController.provisionDigitalInputPin(RaspiPin.GPIO_04, 'MySwitch', PinPullResistance.PULL_DOWN);
```

Issue closed.
