### ISSUE TITLE
Enabling/disabling pin resistors

### ISSUE THREAD

**Issue by zharvey-welltok** [Pi4J/pi4j-v1#371]
Is it possible to enable pullup/pulldown resistors of specific GPIO pins using pi4j? If so, can someone provide a code example of how to do this? Thanks!

**Comment by ribasco** [comment]
See http://pi4j.com/example/listener.html

**Comment by savageautomate** [comment]
Yes.
http://pi4j.com/apidocs/com/pi4j/io/gpio/GpioProvider.html#setPullResistance-com.pi4j.io.gpio.Pin-com.pi4j.io.gpio.PinPullResistance-

Or it can be done while provisioning the pin.
