### ISSUE TITLE
Something wrong with PWM output 

### ISSUE THREAD

**Issue by AlexanderBykin** [Pi4J/pi4j-v1#375]
Hi
i have a problem with pwm on motor driver, when i try to enable one of two motors there is runnig always two
my setup: raspberry pi 3 model b, motor driver controller [L298N](https://goo.gl/RvtCN8), jvm 8, pi4j 1.2-SNAPSHOT

used pins: 
- left motor: GPIO_26, GPIO_04, GPIO_05
- right motor: GPIO_01, GPIO_03, GPIO_02

my source [can be found here](https://github.com/AlexanderShniperson/pi4j_motordrivers)

Instruction:
- [Gradle build tool](https://gradle.org/releases/) needed to build a project
- to build project run command from project folder `gradle installDist`
- to run application `sudo ./build/TankClient/bin/TankClient`

need help to understand what i'm doing wrong.

**Comment by AlexanderBykin** [comment]
@savageautomate 
hi, can you please look at my problem?
thanks

**Comment by eitch** [comment]
@AlexanderShniperson the link to your project is broken

**Comment by AlexanderBykin** [comment]
@eitch oh sorry, this is some typo in link, it is updated now

**Comment by AlexanderBykin** [comment]
looks like GPIO pins somehow related
GPIO 1  // supports PWM0
GPIO 26 // supports PWM0
GPIO 24 // supports PWM1

replaced second engine connection from GPIO_26 to GPIO_24 and now it works fine

**Comment by fclinton** [comment]
Looks like all is good suggest closing @AlexanderShniperson
