### ISSUE TITLE
OrangePI support

### ISSUE THREAD

**Issue by perseptron** [Pi4J/pi4j-v1#379]
Is there any posibility to return to java 1.7, or make separate build with orangePi support on java 7?
pi4j will be priceless if will work on android, but most android don't support java 8, so now it just worth nothing )
Thanks!

**Comment by savageautomate** [comment]
I'm not sure that the binary parts of Pi4J will work on Android.  Check out the pi4j-native project in the repo and you can see there is a bunch of C code compiled into a linux shared library (.so).

**Comment by perseptron** [comment]
if it would be compiled for armeabi, why not? I saw wiringOP library works on Android, but of course in root mode

**Comment by savageautomate** [comment]
**Closed.**  No further activity.
