### ISSUE TITLE
Serial communication randomly adding jump-line when a period is in the String received

### ISSUE THREAD

**Issue by johngamarra** [Pi4J/pi4j-v1#38]
I'm receiving a string from an Arduino ATMega328 every 10 seconds... string is composed of a Temp value and pH value, It contains . (period) characters, for example:

Temp:24.94,PH:7.00

but, sometimes I've receive this information separated in 2 different lines, example:

Temp:25.
00,PH:7.00

or

Temp:24.75,PH:7.
00

It happens randomly, now, I already tested the Arduino Serial output in a RS 232 debugger, conected to a laptop and termite software, the issue never happens, what I really don't know is if is pi4j issue or pi serial port or my connection... so can somebody help me to test if its only me? thanks...

**Comment by savageautomate** [comment]
Hi John,

What does the serial receive code look like?

If you are using the "SerialDataEvent" to receive, please note that Pi4J does not do anything to ensure that events are triggered on line breaks.  Pi4J simply has a thread that monitors the receive data buffer on a regular interval.  If any data is detected, an event is created and the inbound data buffer is emptied.  This could very likely happen in the middle of a line.  

Thanks, Robert

**Comment by johngamarra** [comment]
Hi Robert, code is simple:

```
@Override
public void dataReceived(SerialDataEvent event) {
        Logger.info("Datos: " + event.getData());}
```

I'm gonna do more test with the arduino, but I tested it in the past and no jump-line was present... using RS232 debugger.

log file looks like this

2013-02-24 22:46:15 [Thread-4] com.oc.listener.SensorListener.dataReceived()INFO: Datos: Temp:26.19,PH:7.00
2013-02-24 22:46:26 [Thread-4] com.oc.listener.SensorListener.dataReceived()INFO: Datos: Temp:26.
2013-02-24 22:46:26 [Thread-4] com.oc.listener.SensorListener.dataReceived()INFO: Datos: 13,PH:7.00
2013-02-24 22:46:38 [Thread-4] com.oc.listener.SensorListener.dataReceived()INFO: Datos: Temp:26.13,PH:7.00

So, the SerialDataEvent see it like to diferent events, but it's the same event, it just split it in two... coincidentally in the period char (always).

Also notice I've tried rising the time between data send (1 minute), and is still present...

If someone can test something similar, It would really help. I'm thinking my pi serial pins could be broken or something....

John.

**Comment by savageautomate** [comment]
Hi John,

I believe this is working as designed.  Meaning that we don't control when serial data becomes available, we just have a timer thread running in the background that checks the serial data buffer at a fixed interval.  If any data is available, it is pulled from the buffer and an event is created.  There is no guarantee that is won't split data across multiple events.  Serial data streams in and is not "packetized" or framed at the data layer.

What might be nice is adding feature to look for a particular data character in the data buffer before raising the event, thus providing the user a more controlled/framed data set in the event.
