### ISSUE TITLE
NanoPi2 snapshot

### ISSUE THREAD

**Issue by ghost** [Pi4J/pi4j-v1#381]
Hi,

I have a NanoPi 2 Fire (debian 8) and I noticed that you are working on a 1.2 version for Pi4j and that you have a snapshot of that version. I cannot use the pi4j version 1.1 with my device and I would like to install the 1.2 snapshot. Is there any way I could do that?

Thanks.

**Comment by savageautomate** [comment]
There is a Debian based installer here as well as a simple ZIP file that holds all the precompiled JARs for Pi4J:  http://pi4j.com/download.html

Both released version as well as current snapshot (1.2) are available on this page.
