### ISSUE TITLE
Serial on Ubuntu 14

### ISSUE THREAD

**Issue by psinetron** [Pi4J/pi4j-v1#384]
I use the ubuntu 14 on Raspberry pi2 model b and Neo6 GPS module.
I connect the tx and rx to 8 and 10 pins. But have not any signals from my gps module. When I was tested it on Arduino it perfectly worked. Why no signals on listener? Can I set other GPIO pins to serial data?

**Comment by savageautomate** [comment]
No further activity; issue closed.
