### ISSUE TITLE
why the pi4j.com website has not update for such a long time

### ISSUE THREAD

**Issue by 897180673** [Pi4J/pi4j-v1#393]

**Comment by 897180673** [comment]
the raspbian operator system updates quickly.
the newest version is 2017-09-07 now
but,when we use the rasobain version after 2017-4-10
the console will write " Unable to determine hardware version xxxx"
can you solve this problem?

**Comment by savageautomate** [comment]
this should be resolved in version 1.2, which has finally been fully released.
