### ISSUE TITLE
How can I control ws2812 LED strip via SPI?

### ISSUE THREAD

**Issue by ghost** [Pi4J/pi4j-v1#394]
Hello!

I have SPI-2-5000-AM RGB LED strip that uses ws2812 controller. I want to handle this strip on my RaspberryPi3, but I can't figure out can I do it with pi4j library. I know that there is a python library rpi_ws281x, and I hope that I can do it using Java without low-level programming.

Thank you.

P. S. Sorry for my English

**Comment by savageautomate** [comment]
Closed.

No further activity.  Pi4J does not implement any LED strip controller logic, just the ability to communicate via SPI directly.
