### ISSUE TITLE
Consider switching from GPL? 

### ISSUE THREAD

**Issue by haggy** [Pi4J/pi4j-v1#395]
I wanted to ask if you considered switching off of GPL to something more clear and FOSS friendly (Apache 2, MIT, etc). I look forward to your answer. Thanks!

**Comment by savageautomate** [comment]
Pi4J Version 2.0, now in development is switching from a LGPL license to Apache License, Version 2.
This is acceptable now that Pi4J no longer is statically linking to the WiringPi library which is LGPG.
_(all WiringPi static linking has been removed from version 2.0)_

https://github.com/Pi4J/pi4j/tree/develop/2.0

**Comment by haggy** [comment]
This is huge! Thanks @savageautomate !
