### ISSUE TITLE
GPIOExample sample program does not exit

### ISSUE THREAD

**Issue by HBrydon** [Pi4J/pi4j-v1#4]
When running GPIOExample, it operates as desired (ie. it flashes the LED as described) but the program does not exit.  A Ctrl-C (or equiv) is required to terminate the program.  This doesn't seem like the intended behavior.

Thanks for taking the time to write this code and do the web page.  Excellent stuff, greatly appreciated!

**Comment by savageautomate** [comment]
Thank you for writing up this defect report.  I have seen that behavior and I need to look into the issue further and get it fixed.  No that is not the intended behavior.  I think there is probably a scheduled executor thread still running in the background.  I need to dig deeper into this one.  Thanks, Robert

**Comment by savageautomate** [comment]
Fixed in 0.0.4-SNAPSHOT. The "GpioScheduledExecutorImpl" thread pool was not being shutdown properly on queued task completion.

**Comment by savageautomate** [comment]
The new 0.0.4-SNAPSHOT build is available for testing.  

You can download it from the Maven repository here:
https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/0.0.4-SNAPSHOT/
