### ISSUE TITLE
GPIO listener on Compute module 3 Pi4J

### ISSUE THREAD

**Issue by lucblender** [Pi4J/pi4j-v1#406]
Context of utilisation: compute module 3 with Raspbian Jessi Lite, Java with the Pi4J lib version 1.2-SNAPSHOT. I'm trying to implement a GpioPinListenerDigital on the GPIO_23 like so:

    public class SwitchAm {

        final GpioController gpio = GpioFactory.getInstance();
        final GpioPinDigitalInput myButton = gpio.provisionDigitalInputPin(RCMPin.GPIO_23, PinPullResistance.PULL_DOWN);

        SwitchAm(){

            myButton.setMode(PinMode.DIGITAL_INPUT);
            myButton.setShutdownOptions(true);

            GpioPinListenerDigital listener  = new GpioPinListenerDigital() {
                @Override
                public void handleGpioPinDigitalStateChangeEvent(GpioPinDigitalStateChangeEvent event) {
                    // display pin state on console
                    System.out.println(" --> GPIO PIN STATE CHANGE: " + event.getPin() + " = " + event.getState());
                }
            };

            myButton.addListener(listener);
        }

        boolean getState()
        {
            return myButton.isHigh();
        }
    }

Sadly the listener is never called, but I can still get the correct GPIO state with getState.

I also tested the exact same code on a raspberry pi 3 model b and the listener is working perfectly.

**Comment by savageautomate** [comment]
**Closed.**

This issue has been fixed in latest v1.3-SNAPSHOT build.  The GPIO pins were not getting detected and exported properly for CM3 and CM3+.

I tested and validated input listeners for all GPIO pins (0-45) on a CM3 running the latest RaspberryPi OS, WiringPi v2.60 and Pi4J v1.3-SNAPSHOT.
