### ISSUE TITLE
RCSwitchPi support (RF 433.92MHz)

### ISSUE THREAD

**Issue by niark567** [Pi4J/pi4j-v1#41]
Hi,

I am trying to use rcswitchpi with my pi4j/java programs but nothing exists yet.
This ticket is to integrate rcswitch(pi) to complete the pi4j library (and not reinvent the wheel by adding jna or jni calls to rcswitch aside ^^)

Greetings everyone,

Thanks for your great stuff !

**Comment by niark567** [comment]
rcswitch-pi : https://github.com/r10r/rcswitch-pi

**Comment by niark567** [comment]
as rcswitch-pi is also based on wireingpi and does not brings other library calls, it may "just" be a rewrite and can be included or an addition to pi4j. (I will take a look at it)

**Comment by Death111** [comment]
found this https://github.com/entrusc/Pi-RC-Switch , which implements the send functionality in java, but unfortunately no receive.

**Comment by olealgoritme** [comment]
Any other way to receive RF signals with pi4j ? Very interested

**Comment by savageautomate** [comment]
**Closed.**  No further activity.

As of Pi4J v2.x, IO expansion is provided via pluggable modules and support for specific IO expansion chipsets is outside of the scope of the Pi4J project.
