### ISSUE TITLE
I'm using 64-bit Ubuntu on my pi, but pi4j is 32-bit

### ISSUE THREAD

**Issue by Xsxdot** [Pi4J/pi4j-v1#410]
SEVERE: Unable to load [libpi4j.so] using path: [/lib/raspberrypi/dynamic/libpi4j.so]
java.lang.UnsatisfiedLinkError: /tmp/libpi4j7854506006999061126.so: /tmp/libpi4j7854506006999061126.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)

Can I get 64-bit pi4j?

sorry my chinese english

**Comment by savageautomate** [comment]
I don't have a 64-bit environment running on my RPis.
Can you try building it on your system?

You may need to build and install WiringPi first and make sure its compatible.
http://wiringpi.com/download-and-install/

You will also need to install the latest Apache Maven to build Pi4J: (v3.5.3)
https://www.youtube.com/watch?v=czT2-vKSU6w

Next use GIT to clone the Pi4J repository
``` 
cd ~
git clone https://github.com/Pi4J/pi4j
```
Switch into the project directory and build the project using Maven.
``` 
cd ~/pi4j
mvn clean install -P all-platforms,local-compile
```
Once its finished you should see all SUCCESS messages for each pi4j project:
```
[INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Pi4J :: Parent POM 1.2-SNAPSHOT .................... SUCCESS [  5.444 s]
[INFO] Pi4J :: JNI Native Library ......................... SUCCESS [02:45 min]
[INFO] Pi4J :: Java Library (Core) ........................ SUCCESS [01:00 min]
[INFO] Pi4J :: GPIO Extension ............................. SUCCESS [ 17.270 s]
[INFO] Pi4J :: Device Abstractions ........................ SUCCESS [ 26.444 s]
[INFO] Pi4J :: Java Examples .............................. SUCCESS [ 13.603 s]
[INFO] Pi4J :: Distribution 1.2-SNAPSHOT .................. SUCCESS [ 45.455 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:38 min
[INFO] Finished at: 2018-04-25T13:26:01Z
[INFO] ------------------------------------------------------------------------
```

And the compiled .DEB installer will be here:
```
~/pi4j/pi4j-distribution/target/pi4j-1.2-SNAPSHOT.deb
```
And the individual compiled JARs will be here:
```
~/pi4j/pi4j-distribution/target/distro-contents/lib
```

**Please note that I have never tested Pi4J on a 64-bit system.**

Thanks, Robert

**Comment by Xsxdot** [comment]
OK,I'll try it. 

Thank you very mach!!!

**Comment by jannemec** [comment]
Hi did you succeed? I think more and more 64bit installations will be used.

**Comment by Xsxdot** [comment]
Yes,but I deleted this version Ubuntu.
I'm sorry!

发自我的iPhone


------------------ Original ------------------

**Comment by megahertzon** [comment]
Hi friends, when I'll try to compile on 64 bit ubuntu system, a error appear:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Pi4J :: Parent POM 1.3-SNAPSHOT:
[INFO] 
[INFO] Pi4J :: Parent POM ................................. SUCCESS [ 14.897 s]
[INFO] Pi4J :: JNI Native Library ......................... FAILURE [ 30.239 s]
[INFO] Pi4J :: Java Library (Core) ........................ SKIPPED
[INFO] Pi4J :: GPIO Extension ............................. SKIPPED
[INFO] Pi4J :: Device Abstractions ........................ SKIPPED
[INFO] Pi4J :: Java Examples .............................. SKIPPED
[INFO] Pi4J :: Distribution ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  58.488 s
[INFO] Finished at: 2020-06-30T22:19:37-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (pi4j-build-native-libraries) on project pi4j-native: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/citofonia/pi4j/pi4j-native/build.xml:304: The following error occurred while executing this line:
[ERROR] /home/citofonia/pi4j/pi4j-native/build.xml:210: The following error occurred while executing this line:
[ERROR] /home/citofonia/pi4j/pi4j-native/build.xml:85: exec returned: 127
[ERROR] around Ant part ...<ant inheritRefs="true" target="build-libpi4j.so-local">... @ 4:59 in /home/citofonia/pi4j/pi4j-native/target/antrun/build-pi4j-build-platform-libraries.xml
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (pi4j-build-native-libraries) on project pi4j-native: An Ant BuildException has occured: The following error occurred while executing this line:
/home/citofonia/pi4j/pi4j-native/build.xml:304: The following error occurred while executing this line:
/home/citofonia/pi4j/pi4j-native/build.xml:210: The following error occurred while executing this line:
/home/citofonia/pi4j/pi4j-native/build.xml:85: exec returned: 127
around Ant part ...<ant inheritRefs="true" target="build-libpi4j.so-local">... @ 4:59 in /home/citofonia/pi4j/pi4j-native/target/antrun/build-pi4j-build-platform-libraries.xml


how I can fix them??
Best regards,

Nelson

**Comment by Xsxdot** [comment]
@jannemec I can't see anything from the problem you described. But I found a version I compiled earlier. It might be useful to you.
@megahertzon Do you still need?
Where should I upload?

**Comment by Xsxdot** [comment]
Backup is really the best thing in this world!

**Comment by megahertzon** [comment]
hi friend, can you share me your working version please?

**Comment by Xsxdot** [comment]
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install build-essential
sudo apt-get -y install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
sudo apt-get -y install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
sudo apt-get -y install gcc g++
sudo apt-get -y install less
sudo apt-get -y install make
sudo apt-get -y install ant
sudo apt-get -y install tree
tar zxf 64-pi.tar.gz
tar zxf jdk-arm64.tar.gz
sudo mv jdk1.8.0_171/ /opt/
sudo mv apache-maven-3.5.3 /opt/

[pi4j-1.2-SNAPSHOT.deb.zip](https://github.com/Pi4J/pi4j/files/4855547/pi4j-1.2-SNAPSHOT.deb.zip)


This is my init.sh at the time.
But I also encountered other problems at that time, I have forgotten how to solve it

**Comment by FDelporte** [comment]
FYI @savageautomate has done a lot of work the last days on building a 32 and 64 bit version with Docker for V1.4 and V2. An ongoing process, but you can already find more info on https://v2.pi4j.com/build.

**Comment by megahertzon** [comment]
Great man Xsxdot, your deb package seems to work pi4j on 64bit orange pi SBC

**Comment by Xsxdot** [comment]
Oh yeah!



发自我的iPhone


------------------ Original ------------------

**Comment by savageautomate** [comment]
The `develop/1.4` branch includes binaries for both 32-bit and 64-bit Raspberry Pi. 
The `develop/1.4` branch also includes updated build scripts to compile both 32-bit and 64-bit native libraries either via a Docker container or using ARM cross-compilers.  

See https://github.com/Pi4J/pi4j/pull/494
