### ISSUE TITLE
SPI1 support?

### ISSUE THREAD

**Issue by rmt21** [Pi4J/pi4j-v1#413]
Is SPI1 support for the pi on the horizon? Or am I missing it?

**Comment by xiptos** [comment]
Does pi4j support spi1?

**Comment by Taylorjtt** [comment]
I don't understand why this hasn't been answered yet

**Comment by savageautomate** [comment]
Pi4J does not support SPI1.
Pi4J uses the WiringPi library for low level access including SPI.  WiringPi does not support SPI1.

See:
 - http://wiringpi.com/reference/spi-library/
 - https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPiSPI.c 

This could be something to investigate the possibility of supporting in Pi4J v2 which is not based on WiringPi.
