### ISSUE TITLE
PwmExample hard locks the system after erring out

### ISSUE THREAD

**Issue by edelmanjm** [Pi4J/pi4j-v1#421]
I've been testing to see if I can get PWM working using this library, but encountered what I can only describe as very strange behavior. When running the [PwmExample](https://github.com/Pi4J/pi4j/blob/master/pi4j-example/src/main/java/PwmExample.java) class, the program errors with multiple `NoClassDefFound` exceptions, and the system hard locks, requiring a reboot to restore any functionality.

Removing the `System.console().readLine();` lines allows the program to progress past that point, but it still errors on `gpio.shutdown();`.

I've tried both Oracle and OpenJDK, but both have failed with the same issues.

Unfortunately since the system hard locks, my ability to copy text over (or even get a complete error message) is somewhat limited, so the best I can currently provide is a photo of my screen (taken after running the stock PwmExample.)

![img_4517](https://user-images.githubusercontent.com/19657807/43249120-b7e27a8e-906e-11e8-92ca-f4eee0aae997.jpg)

I'm really not sure what to do, given that this no one else here or anywhere else I can find seems to be facing this issue. As far as I can tell, it's not a hardware issue, since PWM generation works just fine using RPi.GPIO and Python. I thought it might be an issue with my Jar, but it looks intact and the errors are with classes in the standard lib.

**Comment by savageautomate** [comment]
Error class in stack trace `SharedSecrets` is no longer in use in Pi4J v1.4.  

I also recently ran this test with success on Pi4J v1.3 and v1.4.

Although the error really looks like some kinds of JVM error if its not finding `ScheduledExecutorService`
