### ISSUE TITLE
Nullpotint exception when running  PCA9685GpioExample.java and PCA9685GpioServoExample.java

### ISSUE THREAD

**Issue by pg-adm1n** [Pi4J/pi4j-v1#422]
Nullpotint exception when running  PCA9685GpioExample.java and PCA9685GpioServoExample.java,

I had checked the root cause is validatePin() will call getMode(), but the example did't call the setMode() method before getMode().

**Comment by savageautomate** [comment]
Adding missing `export` overloaded method to set pin mode by default at time of pin provisioning.
