### ISSUE TITLE
Shouldn't I2CDeviceImpl be using the I2CBus not the I2CBusImpl?

### ISSUE THREAD

**Issue by salamanders** [Pi4J/pi4j-v1#428]
I think there is a mismatch, wouldn't it use the interface not a specific Impl?
Also, when trying to instantiate, I2CProviderImpl().getBus returns a I2CBus, which can't be passed to the constructor.

... or am I constructing a I2C device completely wrong?

**Comment by savageautomate** [comment]
**Closed.** _(I realize this is an old ticket, just cleaning house.)_

You should not have to instantiate the `**Impl` classes directly.  Use the factory methods to create I2C bus instances.

```
I2CBus bus = I2CFactory.getInstance(I2CBus.BUS_0);
```
