### ISSUE TITLE
hardware version error with latest NOOBs on RaspberryPi 3B+

### ISSUE THREAD

**Issue by shishirtab** [Pi4J/pi4j-v1#429]
I referred http://pi4j.com/example/control.html and used simple code to send high signal to a pin. Getting following error during run although it compiled fine.
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . ControlGpioExample.java

sudo java -classpath .:classes:/opt/pi4j/lib/'*' ControlGpioExample

Error:
Unable to determine hardware version. I see: Hardware	: BCM2835
,
 - expecting BCM2708 or BCM2709.

I checked GPIO version. It is 2.46
WiringPi is also latest one, still facing this issue with Raspberry Pi 3 B+ 
-- 
uname -a
Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux

**Comment by CHTJonas** [comment]
I am also experiencing the same issue 👍 
`Linux raspberrypi 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux`

**Comment by shishirtab** [comment]
Use 1.2 snapshot version. Release build has this issue.

**Comment by haggy** [comment]
What is the estimated release date for the snapshot containing this fix?

**Comment by shishirtab** [comment]
It is already available.

**Comment by savageautomate** [comment]
@haggy 

I'm working on a release build of v1.2 now.  Look for it in a few days.
