### ISSUE TITLE
"GpioPinDigitalInput#addListener" does not accept method references

### ISSUE THREAD

**Issue by Dragas** [Pi4J/pi4j-v1#434]
Hi!

I've been trying to use PI4J as the following:

        GpioController gpio = GpioFactory.getInstance();
        gpio.provisionDigitalInputPin(RaspiPin.GPIO_24, "Digital sound limit pin", PinPullResistance.PULL_UP)
                .addListener(new GpioPinListenerDigital() {
                    @Override
                    public void handleGpioPinDigitalStateChangeEvent(GpioPinDigitalStateChangeEvent event) {
                        
                    }
                });

And it seems to work alright. Although I noticed that `GpioPinListenerDigital` is a single method interface, so I opted to use the following instead:

    public static void main(String args[]) {
        GpioController gpio = GpioFactory.getInstance();
        gpio.provisionDigitalInputPin(RaspiPin.GPIO_24, "Digital sound limit pin", PinPullResistance.PULL_UP)
                .addListener(Main::onGpioDigitalPin24StateChange);
    }

    private static void onGpioDigitalPin24StateChange(GpioPinDigitalStateChangeEvent e) {

    }

But during compile time, I get the following error:

    Error:(58, 17) java: no suitable method found for addListener(Main::onGp[...]hange)
        method com.pi4j.io.gpio.GpioPin.addListener(com.pi4j.io.gpio.event.GpioPinListener...) is not applicable
          (varargs mismatch; com.pi4j.io.gpio.event.GpioPinListener is not a functional interface
              no abstract method found in interface com.pi4j.io.gpio.event.GpioPinListener)
        method com.pi4j.io.gpio.GpioPin.addListener(java.util.List<? extends com.pi4j.io.gpio.event.GpioPinListener>) is not applicable
          (argument mismatch; java.util.List is not a functional interface
              multiple non-overriding abstract methods found in interface java.util.List)

After that, I started looking through sources and found that `GpioListener` indeed is not a functional interface and does not have any methods. This raises the following questions.

1. Can you add analog listeners to digital pins?
    1. Does that make sense?
    2. Are you prevented from doing that?
2. Would it not make more sense to have `addListener(GpioPinListenerDigital...)` on digital pins and `addListaner(GpioPinListenerAnalog...)` on analog pins instead?

Cheers.

**Comment by savageautomate** [comment]
_I realize this is an old issue but I am reviewing issues for the upcoming v1.3 release._  

---

> _Can you add analog listeners to digital pins?
Does that make sense?_

No, not if it is strictly a digital pin.  On some devices pins can be both analog and digital, but would probably need to get provisioned to act on one or the other.  

> _Would it not make more sense to have addListener(GpioPinListenerDigital...) on digital pins and addListaner(GpioPinListenerAnalog...) on analog pins instead?_

I think this implementation is a casualty of _legacy_ and not wanting to break existing interfaces.  Analog support was added to Pi4J later and it was somewhat shoehorned in.  

I believe the concepts and support for ANALOG vs DIGITAL have a much better/cleaner implementation in Pi4V v2.x.  See these examples: https://github.com/Pi4J/pi4j-examples/tree/master/src/main/java/com/pi4j/example/gpio

Functional interfaces and support for lambda expressions for pin events should be supported in Pi4J v2.x.
