### ISSUE TITLE
Orange Pi Zero. Unable to open GPIO edge interface for pin 4: Permission denied

### ISSUE THREAD

**Issue by troublegum** [Pi4J/pi4j-v1#436]
I have Orange Pi Zero v1.5, ARMBIAN 5.65 stable Ubuntu 18.04.1 LTS 4.14.84-sunxi, PI4J VERSION   : 1.2-SNAPSHOT   TIMESTAMP : 2018-04-23 04:22:34 and use WiringOP https://github.com/xpertsavenue/WiringOP-Zero

And I ran an example "sudo /opt/pi4j/examples/orangepi/GpioListenAllExample" and got an exception:
Exception in thread "main" java.lang.RuntimeException: Unable to open GPIO edge interface for pin 4: Permission denied
![image](https://user-images.githubusercontent.com/976635/50820661-4cdd9180-133e-11e9-87b7-5affafe9595a.png)

![image](https://user-images.githubusercontent.com/976635/50820775-95954a80-133e-11e9-83a1-208c10a460cd.png)

![image](https://user-images.githubusercontent.com/976635/50820329-5f0b0000-133d-11e9-9a6f-850e34df92db.png)

**Comment by savageautomate** [comment]
Orange Pi Zero is no longer supported in Pi4J v1.4. 
For more details, please see:
 - https://pi4j.com/1.4/index.html
 - https://github.com/Pi4J/pi4j/blob/master/README.md
