### ISSUE TITLE
Pin.blink() method does not turn off with Pin.low()

### ISSUE THREAD

**Issue by mtmustski** [Pi4J/pi4j-v1#437]
I set a Pin to blink every second with pin.blink(1000) however, when I try to stop the blinking with pin.low(), the pin still continues to blink.  Could this be related to #271?

**Comment by savageautomate** [comment]
**Closed.**

` pin.low()` will not stop the blink operation (_occurring inside an executor thread_), so you must call `pin.blink(0)` to stop the blinking operation.
