### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by miathedev** [Pi4J/pi4j-v1#440]
Actually, it would be interesting for some people how I/O operations with which VM pi4j are fast at most.
So i thought, lets benchmark it.

I tested the pi zero with the standard openjdk-8-headless package running a minimal debian without gpu usage. I got ~28-29kHz with the following code:

```
// create gpio controller
final GpioController gpio = GpioFactory.getInstance();

// provision gpio pin #01 as an output pin and turn on
final GpioPinDigitalOutput pin = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_03, "MyLED",PinState.HIGH);
        
pin.setShutdownOptions(true, PinState.LOW);
        
while(true) {
  pin.toggle();
}
```

Can people that have something else than a pi zero please benchmark his/her device with the code above?
It would be really interesting. I would like to create a comparison table.

Im sorry for my bad english.

**Comment by haggy** [comment]
@miathedev The tool I call [Pins-N-Needles](https://github.com/haggy/pins-n-needles) that I currently made available on my GH, while definitely not a benchmark tool, has shown me how performant Pi4J and java IO with raspberry pi can be. Im able to program and switch circuits involving simple IC's like shift registers __very__ fast. You might find it interesting to play around with while you analyze the performance!

**Comment by savageautomate** [comment]
**Closed**.  Lack of further activity.
