### ISSUE TITLE
SerialPort.java getDefaultPort() throws exception for Raspberry Pi 3 A+

### ISSUE THREAD

**Issue by AlexBelchUK** [Pi4J/pi4j-v1#441]
The raspberry pi 3 A+ /proc/cpuinfo is 

processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: 9020e0
Serial		: 00000000764d8964

------------

The Revision : 9020e0 is not detected as PI 3 A+ and throws UnknownBoard exception

1) File: pi4j/pi4j-core/src/main/java/com/pi4j/system/impl/RaspiSystemInfoProvider.java
    a) Add line: 
        public static final short RPI_MODEL_3A_PLUS = 14;

    b) In static method getBoardType() add new case statement below the case RPI_MODEL_3B_PLUS:
        case RPI_MODEL_3A_PLUS: return SystemInfo.BoardType.RaspberryPi_3A_Plus;

2) File: pi4j/pi4j-core/src/main/java/com/pi4j/system/SystemInfo.java
    a) In the public enum BoardType, add beneath RaspberryPi_3B_Plus, line: 
        RaspberryPi_3A_Plus,

3) File: pi4j/pi4j-core/src/main/java/com/pi4j/io/serial/SerialPort.java
    a) In the getDefaultPort(SystemInfo.BoardType board) change to:
            // ---------------------------
            // RASPBERRY PI MODEL 3B, 3B+, 3A+
            // ---------------------------
            case RaspberryPi_3B:
            case RaspberryPi_3B_Plus: 
            case RaspberryPi_3A_Plus: {
                // if the /dev/ttyS0 port exists, then use it as the default serial port
                File s0ComPort = new File(RaspberryPiSerial.S0_COM_PORT);
                if((s0ComPort.exists())){
                    return RaspberryPiSerial.S0_COM_PORT;
                }
                return RaspberryPiSerial.DEFAULT_COM_PORT;
            }
       
The only other thing to add is that there is a later version of wiringpi 2.48
which may need to be updated for the gpio utility to show the 3 A+ module details
but version 2.46 should be okay for 3 A+ developers.

**Comment by savageautomate** [comment]
Fixed in upcoming v1.3 release.
