### ISSUE TITLE
apt-get update error

### ISSUE THREAD

**Issue by CharlesGodwin** [Pi4J/pi4j-v1#445]
I'm getting this error when I attempt an update

```
apt-get update
Ign:1 http://repository.pi4j.com wheezy InRelease
Err:2 http://repository.pi4j.com wheezy Release
  403  Forbidden [IP: 52.84.85.180 80]
```

**Comment by savageautomate** [comment]
I am actively working on moving all these install and download resources to a secure (HTTPS) server. 
I'll post back when its all up and running.  

Thanks, Robert

**Comment by savageautomate** [comment]
This should be fixed/resolved/working now.  

`http://repository.pi4j.com` should redirect to `https://repository.pi4j.com` now.
