### ISSUE TITLE
Binutils package required on ArchLinux

### ISSUE THREAD

**Issue by vazz3rt** [Pi4J/pi4j-v1#45]
WiringPi is using /usr/bin/readelf which is part of binutils package in ArchLinux. This package isn't installed in base system and java throws error about missing /usr/bin/readelf.

**Comment by glnds** [comment]
Hi i made a pi4j build for Arch Linux. If you're interested here's the link
http://gleenders.blogspot.be/2014/03/pi4j-for-arch-linux.html
