### ISSUE TITLE
Support SX1509

### ISSUE THREAD

**Issue by Misiu** [Pi4J/pi4j-v1#452]
SparkFun has released a great expander - https://www.sparkfun.com/products/13601 that has much more options than MCP23017.
Currently, inside openHAB pi4j is used to support MCP23017.
WIth support for SX1509 we will be able to support it in openHAB.
There is a [library](https://github.com/hoppler/SparkFun-SX1509) in C++ but native support in pi4j would be awesome!

**Comment by savageautomate** [comment]
Pi4J V2 which is currently in development will support an extensibility plugin framework enabling developers to add support for external periphery I/O, add-on boards, I/O chips, "Pi-HATs".  External I/O boards are being removed from the core Pi4J project as the support, maintenance and validation testing has become overwhelming and leads to delays in project releases.  

More info here:
 - https://forum.pi4j.com/topic/3/version-2-0-overview
 - https://v2.pi4j.com/news
