### ISSUE TITLE
PWM output check fails due to wrong operator

### ISSUE THREAD

**Issue by AbelPelser** [Pi4J/pi4j-v1#453]
In [pi4j/pi4j-core/src/main/java/com/pi4j/io/gpio/GpioProviderBase.java:267,](https://github.com/Pi4J/pi4j/blob/03cacc62223cc59b3118bfcefadabab979fd84c7/pi4j-core/src/main/java/com/pi4j/io/gpio/GpioProviderBase.java#L267)
we believe that 
 `if (mode != PinMode.PWM_OUTPUT || mode != PinMode.SOFT_PWM_OUTPUT) {`
should be changed into 
 `if (mode != PinMode.PWM_OUTPUT && mode != PinMode.SOFT_PWM_OUTPUT) {`,

since mode can never be equal to both at the same time. This caused a test scenario to fail for us, halting our compilation process.

**Comment by fclinton** [comment]
I added PR #465 I guess see if it gets merged or fork your own

**Comment by savageautomate** [comment]
**Closed**.  Merged into v1.3 release.
