### ISSUE TITLE
Add support for Rock Pi 4

### ISSUE THREAD

**Issue by TheNetStriker** [Pi4J/pi4j-v1#455]
Would it be possible to add support for the [Rock Pi 4](https://wiki.radxa.com/Rockpi4) to this library?

**Comment by savageautomate** [comment]
CLOSED.  Closing this issue as the Pi4J project moving forward is not directly supporting alternate platforms.  With the release of Pi4J V2, additional platforms can be supported via extensibility plugins.   However, only the Raspberry Pi support will be included in the project's distributions.
