### ISSUE TITLE
我用java写的程序为啥我的树莓派4B为啥不亮？？

### ISSUE THREAD

**Issue by mmnbplus** [Pi4J/pi4j-v1#476]
最新就支持对Raspberry Pi 3A +的支持吗 4B啥时候能有？

**Comment by vowovrz** [comment]
pi4j 1.2版本里留的是wiringPI作者的邮箱，当用户将硬件升级到4B时会报错，报错信息里有wiringPI作者的邮箱，于是这个邮箱收到大量反馈，甚至谩骂，这本不是他的错。大神一怒之下不在开源。

**Comment by savageautomate** [comment]
Pi4J v1.3 release is coming soon and has been tested on RaspberryPi 4B using the _unofficial_ WiringPi v2.60 fork available here. https://github.com/WiringPi/WiringPi

See:
 - https://pi4j.com/1.3/dependency.html
 - https://webtechie.be/post/2020-10-10-pi4j-on-raspberry-pi-4/
