### ISSUE TITLE
Not always work on Pi4

### ISSUE THREAD

**Issue by shailurie** [Pi4J/pi4j-v1#482]
Sometimes GpioPinDigitalOutput remains in high state, and doesnt turned off/on (in case of LEDs)

**Comment by savageautomate** [comment]
This is most likely related to an older version of WiringPi installed on the host system.  I just tested all GPIO digital outputs today on a RPi 4B system using the latest v1.3-SNAPSHOT and WiringPi v2.60 and all tested out working properly.

See:  
- https://pi4j.com/1.3/install.html#WiringPi_Native_Library
- https://webtechie.be/post/2020-10-10-pi4j-on-raspberry-pi-4/
