### ISSUE TITLE
Add support for OrangePiZero

### ISSUE THREAD

**Issue by matyasb** [Pi4J/pi4j-v1#484]
### Issue
Officially add support for OrangePiZero.

### Progress
The following steps need to be completed to officially announce support for the OrangePiZero boards.

- [x]  source OrangePiZero hardware
- [x]  include wiringPi for OrangePiZero in build
- [x]  package wiringPi for OrangePiZero compiled SO libs in JAR
- [x]  test/validate GPIO outputs
- [x]  test/validate GPIO inputs with pull down
- [x]  test/validate GPIO inputs with pull up
- [ ]  test/validate serial communication
- [x]  test/validate I2C communication
- [ ]  test/validate SPI communication
- [x]  add project examples
- [ ]  update project readme
- [ ]  update project documentation

### Summary
Experimental support as been included in the latest 1.3-SNAPSHOT builds for OrangePiZero. Please be aware that this is largely untested at this time.

### Known Issues
Untested; Experimental

**Comment by savageautomate** [comment]
**Closing**.  No further improvements, feature or device support are planned for Pi4J v1.x.   All efforts have been shifted to the new Pi4J v2.x and v1.x is now in maintenance only state.
