### ISSUE TITLE
RaspberryPi 4b compatibility

### ISSUE THREAD

**Issue by paulober** [Pi4J/pi4j-v1#501]
## The www.pi4j.com website does not contain any information about the lib compatibility to rbp4b.
Is this "under construction"?

**Comment by FDelporte** [comment]
Indeed, V1.3 (RPi4 support with Java8), V1.4 (idem Java 11) and V2 (totally reworked with PiGPIO) are work-in-progress. Idem for the new documentation site, see https://v2.pi4j.com/previous-version-v1
