### ISSUE TITLE
[Enhancement] Wifi scan and connection

### ISSUE THREAD

**Issue by LucBerge** [Pi4J/pi4j-v1#508]
It would be nice to be able to:
- Scan Wifis
- Get all the informations about distant Wifis
- Connect to a Wifi
- Disconnect from the current Wifi

I know how to do it using:
- The `/etc/wpa_supplicant/wpa_supplicant.conf` to reference all the known Wifis ssid and password.
- Hash the password using the `wpa_passphrase` command.
- Enable/Disable the wifi using the `sudo ifconfig wlan0 up` or `sudo ifconfig wlan0 down` command.
- Reboot the wifi using the `sudo wpa_cli -i wlan0 reconfigure` command.

I can help you on that but I need your opinion. Do you authorize bash wrappers ?
Thanks

**Comment by FDelporte** [comment]
Hello Luc, thanks for your idea. It doesn't look like a core-pi4j feature but could be an extra/separate Java module. Will take a look again when we move on with V2 of Pi4J.

**Comment by LucBerge** [comment]
I guess it would be better to create a ticket on the v2 repository ? https://github.com/Pi4J/pi4j-v2/issues

**Comment by savageautomate** [comment]
Moved to: https://github.com/Pi4J/pi4j-v2/issues/68
