### ISSUE TITLE
Pi4J v1.4 site generation leaves "$render.eval( $decoration.body.head )" in header

### ISSUE THREAD

**Issue by savageautomate** [Pi4J/pi4j-v1#514]
The site generation (` mvn -N clean site `) for Pi4J v1.4 leaves the text
```javascript
$render.eval( $decoration.body.head )
```
 in the top header/banner section of the page.

See:  https://pi4j.com/1.4/index.html

**Comment by FDelporte** [comment]
Strange indeed, see it also happens on other sites like https://maven.apache.org/skins-archives/maven-fluido-skin-1.5/sidebar/
