### ISSUE TITLE
Internet hotspot gone wrong

### ISSUE THREAD

**Issue by GarethHards** [Pi4J/pi4j-v1#529]
I've tried asking but seem my questions get ignored,unanswered and closed, sorry for posting my issue is what I'm thinking, but perhaps here it can be seen and I can get assisted.

I followed some online help from other questions some proberbly bad advice that just screwed up things for me, I have a pi4 with Ubuntu 19 running on it with a Plex server and Plex client, a FTP server and FileZilla, I put RaspAp on it but had no internet connection on my PC itself on the device that connects to it so I formatted and started over, and am back to where I started, dnsmasq is installed and I tried using my onboard for internet but lost my WiFi tool on the toolbar, and have no way to put it back because it is not appearing in the list, I'm really sick of this and feel I'll need a fresh install now if I can't get past this issue.

My eth0 is not even a LAN like I wanted it to be nor is my WLAN which I earlier also tried to setup as a LAN .

**Comment by GarethHards** [comment]
Thanks

**Comment by FDelporte** [comment]
Hey Gareth, if I understand correctly your question is not related to Pi4J so not sure if this is the best place to get help. Did you try https://stackoverflow.com/? Personally, when I end up with such problems, a clean install is the fastest solution...
