### ISSUE TITLE
J8 pin Different

### ISSUE THREAD

**Issue by alan543** [Pi4J/pi4j-v1#549]
請問為什麼你的J8 - 40way 和官方不一樣
![image](https://user-images.githubusercontent.com/99321232/153319553-6f7aef55-efec-4ccb-afdf-7951b55897af.png)

![image](https://user-images.githubusercontent.com/99321232/153319089-e2f7f616-fb96-4b29-81f2-dcc0848808a8.png)

官方
![image](https://user-images.githubusercontent.com/99321232/153319263-6c120351-939c-41a4-ab1b-e38f33057138.png)

**Comment by FDelporte** [comment]
Google translate tells me this is your question: "Why is your J8 - 40way different from the official one?" ;-)

"Official numbering of the header" = BCM numbering 
Pi4J V1 under the hood uses the WiringPi library which has indeed a different numbering.

On this page this is explained in more detail: https://pi4j.com/getting-started/understanding-the-pins/ and in this image you get both BCM and WiringPi side-by-side

![](https://pi4j.com/assets/getting-started/pins/headerpins_in_header.png)
