### ISSUE TITLE
Initial state for ouput pin provisioning

### ISSUE THREAD

**Issue by ceteras** [Pi4J/pi4j-v1#55]
Hi, 
My hardware is: RaspberryPi 512MB, one led connected to 3.3V by a 1.8K resistor (anode), and to GPIO_07 (cathode).
I can toggle the gpio just fine, I did my blinking led, but I've noticed an issue when initialising. It blinks one short pulse before doing anything else.
If I only run a code that initializes this pin as output, with initial state HIGH (led off), it will first blink for a split second. This looks like the pin is first LOW, then configured as an output, and only then set HIGH.
This short transition could cause undesired behaviour with certain hardware.

These are the versions I use:
 pi4j-0.0.5
java version "1.7.0_40"
Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) Client VM (build 24.0-b56, mixed mode)
I ran sudo apt-get update && sudo apt-get upgrade today (raspbian).

This is the code:
import com.pi4j.io.gpio.GpioController;
import com.pi4j.io.gpio.GpioFactory;
import com.pi4j.io.gpio.GpioPin;
import com.pi4j.io.gpio.GpioPinDigitalInput;
import com.pi4j.io.gpio.GpioPinDigitalOutput;
import com.pi4j.io.gpio.PinDirection;
import com.pi4j.io.gpio.PinMode;
import com.pi4j.io.gpio.PinPullResistance;
import com.pi4j.io.gpio.PinState;
import com.pi4j.io.gpio.RaspiPin;
class led{
        public static void main(String[] args) throws InterruptedException {
        final GpioController gpio = GpioFactory.getInstance();
        GpioPinDigitalOutput myLed = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_07,   // PIN NUMBER
                                                           "My LED",           // PIN FRIENDLY NAME (optional)
                                                           PinState.HIGH);      // PIN STARTUP STATE (optional)
        }
}

Observed behaviour: it blinks once (high-impedance, then LOW, then HIGH).
Expected behaviour: no blink, switch from high-impedance(input) directly to output, HIGH state.

**Comment by savageautomate** [comment]
Fixed in latest 1/0-SNAPSHOT build.  Provisioning a pin caused an "export" of the pin behind the scenes.  Added logic to check for existing exported pin before re-exporting it.
