### ISSUE TITLE
PCIe x1 connector

### ISSUE THREAD

**Issue by alan543** [Pi4J/pi4j-v1#550]
請問圈起來的P & N pin 是原廠線路否有畫錯筆誤
![image](https://user-images.githubusercontent.com/99321232/153383270-8d67debd-e83b-47e8-b54e-28cd4df19c3e.png)

![image](https://user-images.githubusercontent.com/99321232/153382280-cd09d6e0-24a8-4f7f-957d-38b9d757c146.png)

正確
![image](https://user-images.githubusercontent.com/99321232/153383576-381aa21b-e03f-46bd-9a1b-ade53faf584b.png)

**Comment by FDelporte** [comment]
Sorry, not something I can answer as the Pi4J project doesn't provide PCIE access.

**Comment by alan543** [comment]
> 抱歉，我無法回答，因為 Pi4J 項目不提供 PCIE 訪問。

sorry, I don't understand what you mean, I want to express whether the original circuit has drawn P(+)&N(-) backwards,THX

**Comment by alan543** [comment]
> Sorry, not something I can answer as the Pi4J project doesn't provide PCIE access.



> Sorry, not something I can answer as the Pi4J project doesn't provide PCIE access.

sorry, I don't understand what you mean, I want to express whether the original circuit has drawn P(+)&N(-) backwards,THX

**Comment by alan543** [comment]
> Sorry, not something I can answer as the Pi4J project doesn't provide PCIE access.

sorry, I don't understand what you mean, I want to express whether the original circuit has drawn P(+)&N(-) backwards,THX

**Comment by FDelporte** [comment]
I think this is a question that will get a better answer on https://raspberrypi.stackexchange.com/
