### ISSUE TITLE
I2C issue details

### ISSUE THREAD

**Issue by JanJansen47** [Pi4J/pi4j-v1#56]
Got an issue using an I2C application deployed in TomCat.
Maybe someone got similar  issues?  

1) Frequently I observe an error in the I/O (Output at least).  Output changes state also in case NO output is changed in the application (all output in One synchronized Method.)

2) Less frequently (I don't see a relation with my observation above)  I can trace down an exception in the catalina.out logging: 

Exception in thread "Thread-7" java.lang.RuntimeException: java.io.IOException: Error writing to /dev/i2c-1 at address 0x26 to address 0x13. Got -10001.
    at com.pi4j.gpio.extension.mcp.MCP23017GpioProvider.setState(MCP23017GpioProvider.java:254)
    at com.pi4j.io.gpio.impl.GpioPinImpl.setState(GpioPinImpl.java:303)
    at com.pi4j.io.gpio.impl.GpioPinImpl.high(GpioPinImpl.java:211)
    at me.synology.sagittaweb.IO.GPIO_IO.SetOutput(GPIO_IO.java:131)

See the OS and Java details:

---
## .......Alarm system ..OPERATING SYSTEM.....

OS Name : Linux
OS Version : 3.6.11+
OS Architecture : arm
OS Firmware Build : 4f9d19896166f46a3255801bc1834561bf092732 (clean) (release)
## .......Alarm system...JAVA ENVIRONMENT INFO..

Java Vendor : Oracle Corporation
Java Vendor URL : http://java.oracle.com/
Java Version : 1.7.0_07
Java VM : OpenJDK Zero VM
## Java Runtime : OpenJDK Runtime Environment

Last remark: The hardware is custom build: All I/O is via one i2c interface. All outside parts are with opto isolation. But you never know as its handmade....

**Comment by JanJansen47** [comment]
Let the system run several week. The issue reported issue still occurs as well as some unexpected outputs (??) even in the situation where all output was blocked and only inputs remained.  Assume this is some synchronization or locking issue in the Java or the C drivers.  I'm going to try the Lock lock suggestion found elsewhere in the issuelist.

**Comment by JanJansen47** [comment]
Up to now the "strange" IO errors disappeared after using the synchronization hint. Testing is continued.

**Comment by JanJansen47** [comment]
so

**Comment by savageautomate** [comment]
Added locks from SynchronizedDeviceWrapper into I2CDeviceImpl.
Available in latest 1.0-SNAPSHOT build
