### ISSUE TITLE
RuntimeException: Invalid GPIO pin [23]

### ISSUE THREAD

**Issue by morxGrillmeister** [Pi4J/pi4j-v1#57]
Hi,

I tried to use GPIO pin 23 and got this Exception:

java.lang.RuntimeException: Invalid GPIO pin [23]
        at com.pi4j.wiringpi.GpioUtil.export(Native Method)
        at MblUltraSonicPollingExample.main(MblUltraSonicPollingExample.java:120)

Code:
static private final int GpioEcho    = 23;
// use the Broadcom GPIO pin numbers directly with no re-mapping
if (Gpio.wiringPiSetupGpio() == -1) {
  System.out.println(" ==>> GPIO SETUP FAILED");
  return;
}
GpioUtil.export(GpioEcho, GpioUtil.DIRECTION_IN);

**_NOTE**_: It works with 
static private final int GpioEcho    = 17;

System: 
Raspberry PI Model B, Rev 2, Raspian NOOBS
OS Version        :  Linux 3.6.11+
OS Firmware Date  :  Sep  1 2013 23:31:02
Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) Client VM (build 24.0-b56, mixed mode)

**Comment by JanJansen47** [comment]
can you share your code?

**Comment by savageautomate** [comment]
I think this was related to an older version of WiringPi embedded inside the Pi4J libraries.  The latest develop version is now compiling against wiringPi V2 and should support GPIO 0 to 45 (depending on model).
