### ISSUE TITLE
Null pointer exception when running sample program SystemInfoExample

### ISSUE THREAD

**Issue by dudewithasock** [Pi4J/pi4j-v1#58]
Hi,
first I really have to thank you to make pi4j real. It seems to be just the perfect solution for someone like me, who is starting in java and starting with a pi.

I have a similar problem like in an already closed issue Nr. 3, except I get a Null pointer exception in SystemInfoExample (line 100: i guess from NetworkInfo.getIPAddresses())

I am running a PI with Arch Linux 3.6.11-18 with all packages up to date.
The only way hostname prints the IP address is with the -i switch. Might this be a compatibility problem with this specific distribution?

Thanks a lot already.
Martin

PS: Oh, forgot: Installed is Oracle JDK1.7 update 40 hard float.

**Comment by mfkenson** [comment]
https://github.com/Pi4J/pi4j/issues/63
probably the same root cause?
The fix is pending to be merged.

**Comment by savageautomate** [comment]
This is probably a compatibility issue.  Pi4J is built on Raspian.  However, I went ahead and changed the command to "hostname -i" to hopefully be a little more compatible :-)

**Comment by raqua** [comment]
Hi, I just tried this example program on Arch Linux now and I get NullPointerException on line 134:

Exception in thread "main" java.lang.NullPointerException
    at SystemInfoExample.main(SystemInfoExample.java:134)

Problem seems to be caused by:
hostname --all-ip-addresses call int NetworkInfo.class.

Running from CLI:

```
raqua@X:~ 
$ hostname --all-ip-addresses
hostname: unrecognized option '--all-ip-addresses'
Try 'hostname --help' or 'hostname --usage' for more information.

raqua@X:~ 
$ hostname -i                
127.0.0.1 127.0.0.1 

raqua@X:~ 
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether b8:27:eb:f5:28:e8 brd ff:ff:ff:ff:ff:ff
    inet 10.75.69.221/23 brd 10.75.69.255 scope global dynamic eth0
       valid_lft 1173sec preferred_lft 1173sec
    inet6 fe80::ba27:ebff:fef5:28e8/64 scope link 
       valid_lft forever preferred_lft forever

```

**Comment by decowboy** [comment]
I can confirm the issue is still present for me, using the latest piCore (TinyCore) distribution and Pi4J-1.1.
I get the same response as raqua got when trying to run the command that Pi4J runs to fetch the IP addresses.

`$ hostname --all-ip-addresses`
`hostname: unrecognized option '--all-ip-addresses'`
`Try 'hostname --help' or 'hostname --usage' for more information.`

It results in a NullPointerException.
