### ISSUE TITLE
PiFace inputs don't work correctly

### ISSUE THREAD

**Issue by hklbt** [Pi4J/pi4j-v1#59]
Hi,

for testing purposes we connected inputs with ground to always get LOW signal. When I then start the java application which uses the TRUNK-version of pi4j I always get wrong input values. I looked into the code of PiFaceGpioProvider and found out that the input values get initialized and won't get changed until there's an interrupt in the GpioStateMonitor.
Further I found out, that many events don't get recognized in the GpioStateMonitor, when I push and release the buttons often in short time. It seems that pinInterruptB is sometimes even 0 if a state changed and only 1 flag (for 1 input is set) even if I push 2 buttons at the same time.
When I override getState in the following way, the inputs work always:

```
public PinState getState(Pin pin) {
    // call super method to perform validation on pin
    PinState result = super.getState(pin);

    if (pin.getAddress() < GPIO_B_OFFSET) {
        result = getState(pin.getAddress() - GPIO_A_OFFSET, REGISTER_GPIO_A);
    } else {
        result = getState(pin.getAddress() - GPIO_B_OFFSET, REGISTER_GPIO_B);
    }

    log.debug("getState returned " + result + " for pin " + pin);

    return result;
}

private PinState getState(int pinAddress, byte register) {
    byte readResult = read(register);

    PinState pinState;
    if ((readResult & pinAddress) == pinAddress) {
        pinState = PinState.HIGH;
    } else {
        pinState = PinState.LOW;
    }

    return pinState;
}
```

If I remove the interrupts and the corresponding if-statements from GpioStateMonitor, no input events are missing anymore.
Is there any advance to use the interrupts?

Thanks,
hklbt

**Comment by savageautomate** [comment]
I saw the same issue with testing higher speed or simultaneous GPIO inputs.  I was able to leave the main interrupt logic in place to retain most of the optimization logic and simply remove the individual pin interrupt address conditional checks.  This should not degrade performance much as there are no additional/unnecessary SPI read operations with this change.
