### ISSUE TITLE
i2c read bytes sending more bytes than the single localAddress information

### ISSUE THREAD

**Issue by alexpad** [Pi4J/pi4j-v1#62]
Please add this feature as soon as possible.

In I2CDevice interface:

public int read(byte[] writeBuffer, int writeOffset, int writeSize, byte[] readBuffer, int readOffset, int readSize) throws IOException;

In I2CDeviceImpl:

@Override
    public int read(byte[] writeBuffer, int writeOffset, int writeSize, byte[] readBuffer, int readOffset, int readSize) throws IOException {
        int ret = I2C.i2cReadBytes(bus.fd, deviceAddress, writeSize, writeOffset, writeBuffer, readSize, readOffset, readBuffer);
        if (ret < 0) {
            throw new IOException("Error reading from " + makeDescription() + ". Got " + ret + ".");
        }
        return ret;
    }

In I2C class:

public static native int i2cReadBytes(int fd, int deviceAddress, int writeSize, int writeOffset, byte[] writeBuffer, int readSize, int readOffset, byte[] readBuffer);

In com_pi4j_jni_I2C.h:

/*
- Class:     com_pi4j_jni_I2C
- Method:    i2cReadBytes
- Signature: (IIII[BII[B)I
  */
  JNIEXPORT jint JNICALL Java_com_pi4j_jni_I2C_i2cReadBytes
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray, jint, jint, jbyteArray);

In com_pi4j_jni_I2C.c:

/*
- Class:     com_pi4j_jni_I2C
- Method:    i2cReadBytes
- Signature: (IIII[BII[B)I
  */
  JNIEXPORT jint JNICALL Java_com_pi4j_jni_I2C_i2cReadBytes
  (JNIEnv *env, jobject obj, jint fd, jint deviceAddress, jint writeSize, jint writeOffset, jbyteArray writeBytes, jint readSize, jint readOffset, jbyteArray readBytes)
  {
  int i;
  
  int response = ioctl(fd, I2C_SLAVE, deviceAddress);
  if (response < 0) {
      return response - 10000;
  }
  
  // writing writeSize bytes
  jbyte _body = (_env)->GetByteArrayElements(env, writeBytes, 0);
  for (i = 0; i < writeSize; i++) {
    buf[i] = body[i + writeOffset];
  }
  (*env)->ReleaseByteArrayElements(env, writeBytes, body, 0);
  
  response = write(fd, buf, writeSize);
  if (response != writeSize) {
      return response - 20000;
  }
  
  // reading bytes
  response = ioctl(fd, I2C_SLAVE, deviceAddress);
  if (response < 0) {
      return response - 10000;
  }
  
  response = read(fd, buf, readSize);
  if (response > 0) {
      body = (_env)->GetByteArrayElements(env, readBytes, 0);
      for (i = 0; i < size; i++) {
          body[i + readOfset] = buf[i];
      }
      (_env)->ReleaseByteArrayElements(env, readBytes, body, 0);
  }
  
  return response;
  }

**Comment by savageautomate** [comment]
added in 'develop' branch -- better late than never I hope :-)
also the wrappers for wiringPi's I2C interface are also included in the latest sources

**Comment by alexpad** [comment]
Hi Robert,
thank you very much... ciao !

Alessandro.

2014-09-15 1:21 GMT+02:00 Robert Savage notifications@github.com:

> added in 'develop' branch -- better late than never I hope :-)
> also the wrappers for wiringPi's I2C interface are also included in the
> latest sources
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Pi4J/pi4j/issues/62#issuecomment-55543003.

## 

Alessandro
