### ISSUE TITLE
Raspberry PI Simulator as eclipse plugin

### ISSUE THREAD

**Issue by oslucchi** [Pi4J/pi4j-v1#66]
Was this ever considered?
I was having a look at the code including the C library used. It seems to me that writing some hooks into the C library could be a way to make an external simulator (maybe in form of eclipse plugin) to work.

Any thoughts/suggestions if i was to consider this as contribute to PI4J?

**Comment by savageautomate** [comment]
A simulator or maybe network connected daemon is being considered for the next generation of Pi4J.  We do feel that being able to run from IDE would add a significant improvement to the library's functionality and ease of use.

**Comment by SrMouraSilva** [comment]
Look! :D
http://www.raspinloop.org/

**Comment by oslucchi** [comment]
thanks,

Already loved it!

Osvaldo Lucchini
Mob: +39 348 8704431
skype: oslucchi

2016-01-12 12:32 GMT+01:00 Paulo Mateus notifications@github.com:
