### ISSUE TITLE
RPi_UI

### ISSUE THREAD

**Issue by jessical23** [Pi4J/pi4j-v1#67]
Hi there, 

I'm really new to the pi4j libraries and almost nothing I've tried so far is working. I bought the LCD and push button interface from BitWizard (http://www.bitwizard.nl/wiki/index.php/User_Interface) and am trying to display a very simple text string on the display. Below is a sample of the code in my main, any pointers as to where I'm going wrong would be greatly appreciated!

Thanks in advance!

i2cBus = I2CFactory.getInstance(I2CBus.BUS_1);
display = i2cBus.getDevice(0x94);

String sendText = "Hello world";
byte[] sbuffer = sendText.getBytes();
int buflen = sbuffer.length;
int addr = 0x00;
int offset = 0;
display.write(addr, sbuffer, offset, buflen);

**Comment by andypiper** [comment]
Are you seeing any errors, or just seeing no output?

**Comment by jessical23** [comment]
I'm getting "Error writing to /dev/i2c-1 at address 0x94 to address 0x0. Got -10001. at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(i2CDeviceImpl.java:125
at mypackage.SimpleIO1.main(SimpleIO1.java:60)
where line 60 of SimpleIO1 is display.write(addr, sbuffer, offset, buflen);

**Comment by savageautomate** [comment]
I know this is an old thread .. but, I think you need to make sure the I2C driver is loaded and the device address is properly configured on the device/chip.
http://raspi.tv/how-to-set-up-i2c-in-raspbian-on-the-raspberry-pi
