### ISSUE TITLE
WiringPi :Must be root to call wiringPiSetup() Did you forget sudo?

### ISSUE THREAD

**Issue by anzuti** [Pi4J/pi4j-v1#69]
Greetings. I am an AP Computer Science teacher at a local high school in Colombia South America. We always use eclipse in our projects and now we are trying to develop some project using the Raspberry Pi. When I try to run the example program ControlGpioExample.java I get the message:

WiringPi :Must be root to call wiringPiSetup() Did you forget sudo?

I am compiling from the eclipse installed on the raspberry. Can somebody please guide me through a possible solution? 

Thank you very much.

**Comment by rlsutton1** [comment]
This solution here (although for ubuntu, so the paths will probably be wrong) should work

http://stackoverflow.com/questions/2580279/how-do-i-run-my-application-as-superuser-from-eclipse

**Comment by etp123** [comment]
I am an final year BE student.I am first time on qt creator on Rpi, and while using gpio pins i am getting an error which shows
WiringPi :Must be root to call wiringPiSetup() Did you forget sudo?
can anyone help me to rectify this problem

an advance thanks

**Comment by savageautomate** [comment]
The program must be started with admin rights.  This is typically done on the command line using "sudo".  See the "EXECUTE" section on this page:  http://pi4j.com/example/control.html

If you are trying to execute your program from inside an IDE (like Eclipse) you will need to start your IDE with super user privileges.

**Comment by maltzsama** [comment]
I have this same, "wiringPiSetup: Must be root. (Did you forget sudo?)", but I'm compiling  c++ over ssh on my NetBeans IDE, some idea how to solve this problem? We cant do a chown ou chmod to pi use that without sudo?
