### ISSUE TITLE
Need to read two bytes from i2c device

### ISSUE THREAD

**Issue by Ouwekaas** [Pi4J/pi4j-v1#7]
Dear Pi4J,

thanks for this library, although I got a question. With i2ctools I am able to read my temperature sensor correctly. 

pi@raspberrypi ~ $ sudo i2cget -y 1 0x18 0x05 w
0x33c1

It is importpart to use the w option in this command because the register is double buffered. Otherwise I only get c1 value. Now in the I2CDEVICE class I thought I use the method:
read(int address, byte[] buffer, int offset, int size). But if I set the size to 2, I don't get the second value. It wil result in 0.

buffer[0] = -63    ( the c1 in hex )
buffer[1] = 0      This one should be filled with data...but..it isn't  I expect value 

According to my MCP9808 rtfm 0x33c1, 33 is MSB byte and the c1 is the LSB byte.

Here below my little java try out:

Please help, thank you very much. Kind regards Michel.

public class TestSensor {

```
public static void main(String[] args) throws Exception {

    I2CBus i2cBus = I2CFactory.getInstance(I2CBus.BUS_1);
    I2CDevice tempSensor = i2cBus.getDevice(0x18);

    byte[] buffer = new byte[2];

    int amountBytes = tempSensor.read(5, buffer, 0, 2);

    System.out.println("Amount of byte read : " + amountBytes);
    for(byte b : buffer) {
            System.out.println("Data : "+ b +" hex 0x"+Integer.toHexString((b & 0xff)));
    }
}
```

The result of this application..

pi@raspberrypi ~ $ sudo java -jar tempsensor.jar
Nov 20, 2012 10:10:58 PM com.pi4j.util.NativeLibraryLoader load
INFO: Library [pi4j] loaded successfully using embedded resource file: [jar:file:/home/pi/tempsensor.jar!/lib/soft-float/libpi4j.so]
Amount of byte read : 2
Data : -63 hex 0xc1
Data : 0 hex 0x0

**Comment by natdan** [comment]
Hi, I am going to look at it. Currently you have a problem because current implementation read one byte at the time. I'll change it back to read as many as you asked and try to deal with the problems I originally had with it (and reverted back to reading them one by one).

**Comment by Ouwekaas** [comment]
Thank you ;-)

**Comment by natdan** [comment]
Code is now in git. Go and give it a try. Now I know that at least one of following two is wrong:

a) one cannot read bytes successively, reliably from C file handle of i2c device
b) one cannot read bytes successively, reliably from WiiMotionPlus

I really hope it is the second one and that WiiMotionPlus is the one that dictates sending i2c address (in ioctl) followed with device address followed with reading of one byte each time... Or there's something else I've missed. I'll try to investigate it. In the mean time - please let me know if now you can get two bytes at the time from the MCP9808.

**Comment by Ouwekaas** [comment]
I will this evening, let you know the results asap.

**Comment by savageautomate** [comment]
Hi Ouwekaas,  Any results?  Thanks, Robert

**Comment by Ouwekaas** [comment]
Hi,

Sorry for the late response. I have been ill, felt a sleep behind the
steering Wheel and suffered from a car exident. I was hoping going futher
experiment comming week. I just arrived home this weekend.

Kind regards Michel

**Comment by Ouwekaas** [comment]
I tried je 0.0.4 version, but run into an Exception unfortunately... the old code 0.0.3 version works without the second byte.

i@raspberrypi ~ $ sudo java -jar pi4jtest.jar 
Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.pi4j.io.i2c.impl.I2CBusImpl.<init>(I2CBusImpl.java:94)
    at com.pi4j.io.i2c.impl.I2CBusImpl.getBus(I2CBusImpl.java:70)
    at com.pi4j.io.i2c.I2CFactory.getInstance(I2CFactory.java:53)
    at nl.pikkasoft.tempsensor.test.TestSensor.main(TestSensor.java:14)
Caused by: java.lang.NullPointerException
    at com.pi4j.util.NativeLibraryLoader.load(NativeLibraryLoader.java:225)
    at com.pi4j.jni.I2C.<clinit>(I2C.java:55)
    ... 4 more

Just discovered I do not know how to handje git sources.. please could you build for me a 0.0.4 jar file? In the mean time I gonna learn myself how to handje git sources.... :(

**Comment by natdan** [comment]
I'll have a quick look at it later today, but I am sure it is a problem in a build. 

I am just curious - how did you get pi4j library: did you build it yourself from the source, refer to it in your maven project or just used jar file directly? (hm - last two should do the same thing)

**Comment by Ouwekaas** [comment]
I tried to use te library because I couldn't find the 0.0.4 jar file.

**Comment by natdan** [comment]
What does that mean?

How did you organise your project - is it a maven build or you just use IDE like Eclipse or Idea?

BTW jar file should be in: https://oss.sonatype.org/content/repositories/snapshots/com/pi4j/pi4j-core/0.0.4-SNAPSHOT/ - take the latest from there.

**Comment by Ouwekaas** [comment]
I didn't know or didn't looked good enought. I happy to get the new Jar file.

The result is, this is working! Thank you ! ;-)

**Comment by Ouwekaas** [comment]
pi@raspberrypi ~ $ sudo java -jar pi4jtest.jar 
Dec 11, 2012 1:09:40 PM com.pi4j.util.NativeLibraryLoader load
INFO: Library [pi4j] loaded successfully using embedded resource file: [jar:file:/home/pi/pi4jtest.jar!/lib/soft-float/libpi4j.so]
Amount of byte read : 2
Data : -64 hex 0xc0
Data : -27 hex 0xe5

pi@raspberrypi ~ $ sudo i2cget -y 1 0x18 0x05 w
0xe5c0

**Comment by natdan** [comment]
Cool! I am glad it worked out. 

But, if you want - I can give you a hand setting up your project in such way you never get to this point again. That is why I asked you how do you develop it/build it. 

One (not so bad way) is to set up a maven project, describe dependency to pi4j-core in it and let it do the rest. All you need to do in that case is to increment version of pi4j-core jar to match the latest and let maven do the rest for you. It works quite well with Eclipse and with IntelliJ Idea. 

it is quick and I don't mind making an example for you and attach it here if you want and explain how to keep it in sync with your IDE...

**Comment by Ouwekaas** [comment]
Hello Natdan,

My apologies for my mistakes. I just being a Java programmer for 2 year on my company, besides of 14 year Senior Cisco IP Telephony job ;-) And I have to figure it out all on my self.

I use Eclipse Java EE IDE on Mac OSX
Juno SR1, build id 20121004-1855

I never used GITHUB or similar.  I understand I should focus on Maven instead of Git. An example project would be much appreciated.

Thanking you in advance.

Kind regards Michel.

**Comment by natdan** [comment]
No apologies and I am not sure you made any mistakes. This is only like raising it to the next level! :)

Anyway here's short idea - get maven - download it and 'install' it. By install you can just download .zip or tar.gz and unpack it to some directory. Set MAVEN_HOME env variable to point to dir you unpacked maven and add MAVEN_HOME/bin to your PATH env variable. If you have problems with it - let me know (along which OS you are using).

Start with having following directory structure:

your-project-name/
    src/
    src/main/
    src/main/java/
    src/main/resources/
    src/test/
    src/test/java/
    src/test/resources/

Create pom.xml file in your project dir with, for instance, following content:

``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>pi4jprojects</groupId>
  <artifactId>pi4jtest</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>pi4jtest</name>

  <dependencies>

    <dependency>
      <groupId>com.pi4j</groupId>
      <artifactId>pi4j-core</artifactId>
      <version>0.0.4-SNAPSHOT</version>
    </dependency>

  </ddependencies>
</project>
```

(I think this is enough for minimal project)

And then from your project dir you can type:

> mvn clean install

to build the project. Or alternatively - to make Eclipse project so you can import it in Eclipse as existing project:

> mvn eclipse:clean eclipse:eclipse

Don't forget to type above line each time you change pom.xml

**Comment by Ouwekaas** [comment]
Thanks, I gonna try this very soon ;-)

**Comment by natdan** [comment]
Check it again - I had to play with editing to get pom.xml come out properly! O: )

Now I just need to find a way to pass you a .tgz file of existing project of mine...
