### ISSUE TITLE
 Error writing to /dev/i2c-1 at address 0x41. Got -20001.

### ISSUE THREAD

**Issue by ollio** [Pi4J/pi4j-v1#71]
When I use the block write method of the I2CDevice:

``` java
i2CDevice.write(data, 0, data.length)
```

I get the following error:

```
 Error writing to /dev/i2c-1 at address 0x41. Got -20001.
```

If I write byte by byte and add a sleep it works better:

``` java
for (byte b : data) {
      i2CDevice.write(b);
      sleep(1);
}
```

**Comment by ghost** [comment]
Same issue here. Thread.sleep(1)ing between every byte seems to mysteriously work.

Trying to send a single magic string to an ATTiny84 on a low baud rate (10000).

**Comment by savageautomate** [comment]
Please try the latest 1.0-SNAPSHOT build.  Sync/locks added around I2C R/W methods.
https://github.com/Pi4J/pi4j/commit/4df9a311285b2ca7f4e9fa3437964f56351a1885
