### ISSUE TITLE
I2CDevice read() documentation/impl mismatch describing values

### ISSUE THREAD

**Issue by ayeseeem** [Pi4J/pi4j-v1#73]
The javadocs for I2CDevice read() and I2CDeviceImpl read() both say

> Result is between -128 and 127.

But the impl uses `I2C` `i2cReadByteDirect()` and then checks that the result isn't less than 0.
So the javadocs or the impl are wrong.

Given that `I2C` `i2cReadByteDirect()` says:

> positive number (or zero) to 255 if read was successful. Negative number if reading failed.

I conclude that it's the javadocs for `I2CDevice` `read()` and `I2CDeviceImpl` `read()` that are wrong

**Comment by ayeseeem** [comment]
https://github.com/Pi4J/pi4j/blob/master/pi4j-core/src/main/java/com/pi4j/io/i2c/impl/I2CDeviceImpl.java

https://github.com/Pi4J/pi4j/blob/master/pi4j-core/src/main/java/com/pi4j/jni/I2C.java

**Comment by savageautomate** [comment]
fixed javadoc error, closed.
