### ISSUE TITLE
add support for nRF24L01 transceiver

### ISSUE THREAD

**Issue by mfkenson** [Pi4J/pi4j-v1#77]
I come from arduino platform and just moved to the pi platform.
I've got plenty of sensors/transceiver (SPI/I2C based) and would like to port them to the Pi platform using the Pi4J library.

Any hints/direction for me to start? thanks!

**Comment by rlsutton1** [comment]
you might like to look at my git, I've implemented a few devices over I2C...

https://github.com/rlsutton1/piBot/blob/master/piBot/src/main/java/com/pi4j/gpio/extension/adafruit/ADS1115.java

**Comment by mfkenson** [comment]
thank you! i will implement it with your sample as reference!

**Comment by savageautomate** [comment]
more examples can also be bound in the gpio-extension project in the Pi4J sources.
https://github.com/Pi4J/pi4j/tree/develop/pi4j-gpio-extension/src/main/java/com/pi4j/gpio/extension
