### ISSUE TITLE
pi4j Serial flush truncates pending written data

### ISSUE THREAD

**Issue by TheJaddix** [Pi4J/pi4j-v1#79]
Hello iam using pi4j for serial communication. (DEFAULT_COM_PORT, 9600 boud)
After five serial writes with a total amount of aprox 60 bytes data
i use flush to ensure that all data being send.
But then the data is truncated, most times only the first 16 bytes are send.
Ive inserted a pause (by Thread.sleep) of 110ms between the last write and
the flush, then all data is send correctly.
Lower values for the pause causes data loss,
bigger values (guess what) working fine !

Is it a bug of pi4j or a bug of underling codes ?

  TheJaddix

**Comment by dieKatze88** [comment]
I was able to reproduce this, at a much higher data rate. Calling flush() would immediately delete the contents of the buffer, without sending them.

**Comment by savageautomate** [comment]
Well, this surprised me, I thought it was a bug too, but after trying to get to the bottom of it, it seems that "flush" which is calling "tc_flush" in the native code is intended to discard data on the receive buffer, the transmit buffer or both.  (both in the way wiringPi implements tc_flush)

> tcflush() discards data written to the object referred to by fd but not transmitted, or data received but not read, depending on the value of queue_selector:
> 
> TCIFLUSH
> flushes data received but not read.
> TCOFLUSH
> flushes data written but not transmitted.
> TCIOFLUSH
> flushes both data received but not read, and data written but not transmitted.

REF: http://pubs.opengroup.org/onlinepubs/7908799/xsh/tcflush.html

I have updated the comments to reflect this usage.
