### ISSUE TITLE
JDK1.7 to JDK1.8

### ISSUE THREAD

**Issue by varadig** [Pi4J/pi4j-v1#80]
Hi,

can you help me, how can I setup the maven builder, to change from JDK1.7 to JDK1.8 because I have to use that one.

Thanks a lot, and sorry for my english.

[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.pi4j:pi4j-core:jar:0.0.5
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 74, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 182, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 68, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.pi4j:pi4j-example:jar:0.0.5
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 66, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 60, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.pi4j:pi4j-service:bundle:0.0.5
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 62, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 56, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.pi4j:pi4j-gpio-extension:jar:0.0.5
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 55, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 49, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.pi4j:pi4j-device:jar:0.0.5
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 61, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 55, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.pi4j:pi4j-distribution:pom:0.0.5
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Pi4J :: Parent POM
[INFO] Pi4J :: Java Library (Core)
[INFO] Pi4J :: GPIO Extension
[INFO] Pi4J :: Device Abstractions
[INFO] Pi4J :: Java Examples
[INFO] Pi4J :: OSGi Service
[INFO] Pi4J :: Distribution
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pi4J :: Parent POM 0.0.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- license-maven-plugin:1.3:update-file-header (append-license-file-headers) @ pi4j-parent ---
[INFO] Process header 'sql'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'jsp'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'apt'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'php'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'ftl'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'rst'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'java'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'xml'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'properties'
[INFO]  - using Apache License version 2.0
[WARNING] No file to scan.
[INFO]
[INFO]
[INFO] --- license-maven-plugin:1.3:update-project-license (update-project-license) @ pi4j-parent ---
[INFO]
[INFO] --- build-helper-maven-plugin:1.7:attach-artifact (attach-artifacts) @ pi4j-parent ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pi4j-parent ---
[INFO] Installing /Volumes/GABI/Develop/Java/pi4j/pom.xml to /Users/varadig/.m2/repository/com/pi4j/pi4j-parent/0.0.5/pi4j-parent-0.0.5.pom
[INFO] Installing /Volumes/GABI/Develop/Java/pi4j/LICENSE.txt to /Users/varadig/.m2/repository/com/pi4j/pi4j-parent/0.0.5/pi4j-parent-0.0.5-license.txt
[INFO] Installing /Volumes/GABI/Develop/Java/pi4j/NOTICE.txt to /Users/varadig/.m2/repository/com/pi4j/pi4j-parent/0.0.5/pi4j-parent-0.0.5-notice.txt
[INFO] Installing /Volumes/GABI/Develop/Java/pi4j/README.md to /Users/varadig/.m2/repository/com/pi4j/pi4j-parent/0.0.5/pi4j-parent-0.0.5-readme.md
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pi4j-parent ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pi4J :: Java Library (Core) 0.0.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.5.1:copy (copy-license) @ pi4j-core ---
[INFO] Configured Artifact: com.pi4j:pi4j-parent:license:0.0.5:txt
[INFO] Configured Artifact: com.pi4j:pi4j-parent:notice:0.0.5:txt
[INFO] Configured Artifact: com.pi4j:pi4j-parent:readme:0.0.5:md
[INFO] Copying LICENSE.txt to /Volumes/GABI/Develop/Java/pi4j/pi4j-core/target/LICENSE.txt
[INFO] Copying NOTICE.txt to /Volumes/GABI/Develop/Java/pi4j/pi4j-core/target/NOTICE.txt
[INFO] Copying README.md to /Volumes/GABI/Develop/Java/pi4j/pi4j-core/target/README.md
[INFO]
[INFO] --- maven-dependency-plugin:2.5.1:copy (copy) @ pi4j-core ---
[INFO] Configured Artifact: com.pi4j:pi4j-native:hard-float:0.0.5:so
[INFO] Configured Artifact: com.pi4j:pi4j-native:soft-float:0.0.5:so
[INFO] Copying pi4j-native-0.0.5-hard-float.so to /Volumes/GABI/Develop/Java/pi4j/pi4j-core/target/lib/hard-float/libpi4j.so
[INFO] Copying pi4j-native-0.0.5-soft-float.so to /Volumes/GABI/Develop/Java/pi4j/pi4j-core/target/lib/soft-float/libpi4j.so
[INFO]
[INFO] --- license-maven-plugin:1.3:update-file-header (append-license-file-headers) @ pi4j-core ---
[INFO] Will search files to update from root /Volumes/GABI/Develop/Java/pi4j/pi4j-core/src/main/java
[INFO] Will search files to update from root /Volumes/GABI/Develop/Java/pi4j/pi4j-core/src/test
[INFO] Process header 'jsp'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'sql'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'apt'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'php'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'ftl'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'rst'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'java'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'xml'
[INFO]  - using Apache License version 2.0
[INFO] Process header 'properties'
[INFO]  - using Apache License version 2.0
[INFO] Scan 119 files header done in 370.281ms.
[INFO] All files are up-to-date.
[INFO]
[INFO] --- build-helper-maven-plugin:1.7:add-resource (embed-jni-native-resource) @ pi4j-core ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pi4j-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] skip non existing resourceDirectory /Volumes/GABI/Develop/Java/pi4j/pi4j-core/src/main/resources
[INFO] Copying 2 resources to lib
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ pi4j-core ---
[INFO] Compiling 103 source files to /Volumes/GABI/Develop/Java/pi4j/pi4j-core/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
javac: invalid target release: 1.7
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Pi4J :: Parent POM ................................ SUCCESS [  1.600 s]
[INFO] Pi4J :: Java Library (Core) ....................... FAILURE [  1.906 s]
[INFO] Pi4J :: GPIO Extension ............................ SKIPPED
[INFO] Pi4J :: Device Abstractions ....................... SKIPPED
[INFO] Pi4J :: Java Examples ............................. SKIPPED
[INFO] Pi4J :: OSGi Service .............................. SKIPPED
[INFO] Pi4J :: Distribution .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.373 s
[INFO] Finished at: 2014-03-08T08:32:41+01:00
[INFO] Final Memory: 14M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project pi4j-core: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: invalid target release: 1.7
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pi4j-core

**Comment by valdar** [comment]
May be you can change the java target and source version on line 432 and 433 of the POM file,
but I don't know if that will solve your problem...

**Comment by varadig** [comment]
I tried that, but just this happened:
[ERROR] javac: invalid target release: 1.8

But now I found I don't need to rebuild, I can use with the latest compiled version :)
but thanks
