### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.pi4j.wiringpi.Gpio.wiringPiSetup 

### ISSUE THREAD

**Issue by karopodgajecki** [Pi4J/pi4j-v1#83]
Full log stack:

org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.UnsatisfiedLinkError: com.pi4j.wiringpi.Gpio.wiringPiSetup()I
    org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1259)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:945)
    org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:915)
    org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:811)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:796)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
root cause

java.lang.UnsatisfiedLinkError: com.pi4j.wiringpi.Gpio.wiringPiSetup()I
    com.pi4j.wiringpi.Gpio.wiringPiSetup(Native Method)
    com.pi4j.io.gpio.RaspiGpioProvider.<init>(RaspiGpioProvider.java:47)
    com.pi4j.io.gpio.GpioFactory.getDefaultProvider(GpioFactory.java:102)
    com.pi4j.io.gpio.impl.GpioControllerImpl.<init>(GpioControllerImpl.java:67)
    com.pi4j.io.gpio.GpioFactory.getInstance(GpioFactory.java:85)
    pl.raspberrypi.mvc.HelloController.home2(HelloController.java:48)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
    org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:439)
    org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:427)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
    org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:915)
    org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:811)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:796)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)

Used it in easy spring mvc project  project:

public class HelloController {

```
private final static Logger logger = Logger.getLogger(HelloController.class);

@Autowired
TestService testService;

@RequestMapping(method = RequestMethod.GET)
public String printWelcome(ModelMap model) {

    model.addAttribute("message", "Hello world!");
    return "hello";
}

@RequestMapping(value = "/test/1", method = RequestMethod.GET)
public String home(HttpServletRequest request, ModelMap model) {

    GpioController gpio = GpioFactory.getInstance();
    GpioPinDigitalOutput outputPin = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_07, "MyLED", PinState.LOW);
    outputPin.high();
    return "hello";
}

@RequestMapping(value = "/test/2", method = RequestMethod.GET)
public String home2(HttpServletRequest request, ModelMap model) {

    GpioController gpio = GpioFactory.getInstance();
    GpioPinDigitalOutput outputPin = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_07, "MyLED", PinState.LOW);
    outputPin.low();
    return "hello";
}
```

}

**Comment by savageautomate** [comment]
I think there is some issue where the native library is not getting resolved/loaded.  
You can see that the error is pointing to this line of code:
https://github.com/Pi4J/pi4j/blob/master/pi4j-core/src/main/java/com/pi4j/wiringpi/Gpio.java#L158

This method is attempting to call a JNI method into the native "libpi4j.so" library.  

Here is an old thread with more details on what is going on:
https://github.com/Pi4J/pi4j/issues/1

Basically there is a NativeLibraryLoader class that must not be finding the "libpi4j.so" in the classpath.
https://github.com/Pi4J/pi4j/blob/master/pi4j-core/src/main/java/com/pi4j/util/NativeLibraryLoader.java

You can set the system property "pi4j.debug=true" and Pi4J will write out a log file of what is going on in the native library loading process. 

You may have to end up extracting the "libpi4j.so" from the pi4j.jar and placing it in a fixed location and then configuring your web server to include a specific java.library.path.
"java -Djava.library.path=/var/lib/java"

**Comment by savageautomate** [comment]
closed. no further updates.
