### ISSUE TITLE
Tomcat deploy and "java.lang.UnsatisfiedLinkError: com.pi4j.wiringpi.Serial.serialOpen"

### ISSUE THREAD

**Issue by cacodemon79** [Pi4J/pi4j-v1#85]
Hi friends,
I have a strange problem with Tomcat 7 and Pi4J.

I have a very simple servlet that prints on a web page the data read from the serial port (after 10 seconds).

I deploy WAR trough ANT build.xml on a remote TOMCAT 7 (installed in a RASPBERRY PI environment).

When i start TOMCAT for the first time, all works very well. Serial data are read and written on a web page.

May 21, 2014 10:27:19 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-bio-8080"]
May 21, 2014 10:27:19 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina
May 21, 2014 10:27:20 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-bio-8080"]
May 21, 2014 10:27:20 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-bio-8080"]
May 21, 2014 10:27:40 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
May 21, 2014 10:27:41 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 14641 ms
May 21, 2014 10:27:42 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
May 21, 2014 10:27:42 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.28
May 21, 2014 10:27:42 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/host-manager.xml
May 21, 2014 10:27:52 PM org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [125] milliseconds.
May 21, 2014 10:27:52 PM org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [125] milliseconds.
May 21, 2014 10:27:53 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/manager.xml
May 21, 2014 10:27:56 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/Test.war
May 21, 2014 10:27:59 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/Enose.war
May 21, 2014 10:28:02 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT
May 21, 2014 10:28:46 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
May 21, 2014 10:28:46 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 64767 ms

The problem arises when, after modifying the source code, I deploy again the WAR file to TOMCAT.

May 21, 2014 10:41:20 PM org.apache.catalina.startup.HostConfig checkResources
INFO: Undeploying context [/Test]
May 21, 2014 10:41:24 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/Test.war

In this case, when I recall the same servlet, I got an exception 

May 21, 2014 10:43:25 PM com.pi4j.util.NativeLibraryLoader loadLibraryFromResource
WARNING: The temporary file already exists [/tmp/tomcat7-tomcat7-tmp/libpi4j.so]; attempting to delete it now.
May 21, 2014 10:43:26 PM com.pi4j.util.NativeLibraryLoader load
SEVERE: Failed to load library [pi4j] using the System.load(file) method using embedded resource file: [jar:file:/var/lib/tomcat7/webapps/Test/WEB-INF/lib/pi4j-core.ja$
May 21, 2014 10:43:26 PM com.pi4j.util.NativeLibraryLoader load
SEVERE: ERROR:  The native library [pi4j : libpi4j.so] could not be found in the JVM library path nor could it be loaded from the embedded JAR resource file; you may n$
java.lang.UnsatisfiedLinkError: com.pi4j.wiringpi.Serial.serialOpen(Ljava/lang/String;I)I
        at com.pi4j.wiringpi.Serial.serialOpen(Native Method)
        at com.pi4j.io.serial.impl.SerialImpl.open(SerialImpl.java:81)
        at Seriale.apri(Seriale.java:54)
        at Test.doGet(Test.java:42)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)

I can't understand why the first time all works but the second not!

If I restart TOMCAT, all re-works very well (but always and only for the first time ... after a new deploy the problem returns).

I also tried with "-Djava.library.path=/var/lib/java" method but nothing changed.

Here is my source code:

---

SERVLET

---

protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

```
    try {

        response.setContentType("text/html");
        PrintWriter writer = response.getWriter();
        writer.println("<html>");
        writer.println("<head><title>TEST</title></head>");
        writer.println("<body>");


        Seriale seriale = new Seriale();
        seriale.apri();
        seriale.leggi();
        Thread.sleep(10000);
        seriale.chiudi();

        writer.println("<p><b>DATI SERIALE:</b></p>" + seriale.getBuffer());


        writer.println("</body>");
        writer.println("</html>");
        writer.close();
    }
    catch(UnsatisfiedLinkError ule) {
        ule.printStackTrace();
    }
    catch(InterruptedException ie) {
        ie.printStackTrace();
    }
    catch(SerialPortException spe) {
        spe.printStackTrace();
    }
    catch(IllegalStateException ise){
        ise.printStackTrace();                    
    }
    catch(Exception e) {
        e.printStackTrace();
    }

}
```

---

Class SERIALE

---

public class Seriale {

```
private Serial seriale;
private int velocita;
private String buffer;

public Serial getSeriale() {
    return seriale;
}

public void setSeriale(Serial seriale) {
    this.seriale = seriale;
}

public int getVelocita() {
    return velocita;
}

public void setVelocita(int velocita) {
    this.velocita = velocita;
}

public String getBuffer() {
    return buffer;
}

public void setBuffer(String buffer) {
    this.buffer = buffer;
}


public Seriale() {

    //leggo le impostazioni della seriale
    ResourceBundle impostazioniSeriale =  ResourceBundle.getBundle("risorse.seriale");
    velocita = Integer.parseInt(impostazioniSeriale.getString("velocita"));

    //crea un'istanza della classe di comunicazione seriale
    seriale = SerialFactory.createInstance();

    buffer = "";
}

public void apri() {

    seriale.open(Serial.DEFAULT_COM_PORT, velocita);
}

public void leggi() {

    // create and register the serial data listener
    seriale.addListener(new SerialDataListener() {
        @Override
        public void dataReceived(SerialDataEvent event) {
            // print out the data received to the console
            buffer += event.getData();
        }            
    });
}

public void chiudi() {

    seriale.shutdown();
    seriale.close();

}
```

---

BUILD.XML

---

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ANT_BUILD.XML>

<project name="Test" basedir="." default="deploy">

```
<!-- File di configurazione -->
<property file="build.properties"/>

<property name="src.dir" value="src"/>
<property name="build" value="${basedir}/build"/>
<property name="web.dir" value="WebContent"/>
<property name="buildweb.dir" value="${web.dir}/WEB-INF/classes"/>
<property name="webxml.dir" value="${web.dir}/WEB-INF/web.xml"/>
<property name="name" value="Test"/>
<property name="tomcat.manager.url" value="http://${tomcat.server.url}:${tomcat.server.port}/manager/text"/>

<path id="master-classpath">
    <fileset dir="${web.dir}/WEB-INF/lib">
        <include name="*.jar"/>
    </fileset>
    <fileset dir="${appserver.lib}">
        <include name="servlet-api.jar"/>
    </fileset>
    <pathelement path="${buildweb.dir}"/>
</path>

<target name="clean" description="Clean output directories">
    <delete dir="${buildweb.dir}" includeemptydirs="true" failonerror="false" />
    <delete file="${name}.war" quiet="true" />
</target>

<target name="build" depends="clean" description="Compile java files">
    <mkdir dir="${buildweb.dir}"/>
    <javac destdir="${buildweb.dir}" srcdir="${src.dir}" debug="true" deprecation="false" optimize="false" failonerror="true" includeantruntime="false">
        <src path="${src.dir}"/>
        <classpath refid="master-classpath"/>
    </javac>
    <!-- Copio nella directory di build i file non presi in considerazione da javac (es. resource bundle) escluso i file java sorgenti -->
    <copy todir="${buildweb.dir}">
        <fileset dir="${src.dir}" excludes="**/*.java" />
    </copy>
</target>

<target name="deployfiles" depends="build" description="Deploy application files to a local server">
    <copy todir="${deploy.path}/${name}" preservelastmodified="true">
        <fileset dir="${web.dir}">
            <include name="**/*.*"/>
        </fileset>
    </copy>
</target>

<target name="createwar" depends="build" description="Create application WAR file">
    <war destfile="${name}.war" webxml="${webxml.dir}">
        <fileset dir="${web.dir}">
            <include name="**/*.*"/>
        </fileset>
            <!--
            <lib dir="${web.dir}/WEB-INF/lib"/>
            <classes dir="${buildweb.dir}"/>
            -->
    </war>
</target>

<target name="deploywar" depends="build" description="Deploy application as a WAR file to a local server with copy command">
    <war destfile="${name}.war" webxml="${webxml.dir}">
        <fileset dir="${web.dir}">
            <include name="**/*.*"/>
        </fileset>
        <!--
        <lib dir="${web.dir}/WEB-INF/lib"/>
        <classes dir="${buildweb.dir}"/>
        -->
    </war>
    <copy todir="${deploy.path}" preservelastmodified="true">
        <fileset dir=".">
            <include name="*.war"/>
        </fileset>
    </copy>
    <delete file="${name}.war" quiet="true" />
</target>

<path id="catalina-ant-classpath">
    <!-- We need the Catalina jars for Tomcat -->
    <!--  * for other app servers - check the docs -->
    <fileset dir="${appserver.lib}">
        <include name="catalina-ant.jar"/>
        <include name="tomcat-coyote.jar"/>
        <include name="tomcat-util.jar"/>
    </fileset>
</path>

<!-- Configure the custom Ant tasks for the Manager application -->
<taskdef name="deploy" onerror="fail" classname="org.apache.catalina.ant.DeployTask">
    <classpath refid="catalina-ant-classpath"/> 
</taskdef>
<taskdef name="list" classname="org.apache.catalina.ant.ListTask">
    <classpath refid="catalina-ant-classpath"/> 
</taskdef>
<taskdef name="reload" classname="org.apache.catalina.ant.ReloadTask">
    <classpath refid="catalina-ant-classpath"/> 
</taskdef>
<taskdef name="findleaks" classname="org.apache.catalina.ant.FindLeaksTask">
    <classpath refid="catalina-ant-classpath"/> 
</taskdef>
<taskdef name="resources" classname="org.apache.catalina.ant.ResourcesTask">
    <classpath refid="catalina-ant-classpath"/> 
</taskdef>
<taskdef name="start" classname="org.apache.catalina.ant.StartTask">
    <classpath refid="catalina-ant-classpath"/> 
</taskdef>
<taskdef name="stop" classname="org.apache.catalina.ant.StopTask">
    <classpath refid="catalina-ant-classpath"/> 
</taskdef>
<taskdef name="undeploy" onerror="fail" classname="org.apache.catalina.ant.UndeployTask">
    <classpath refid="catalina-ant-classpath"/> 
</taskdef>

<target name="deploy" depends="undeploy,createwar" description="Deploy application as a WAR file to any server (both local and remote) through Tomcat Manager">
    <deploy url="${tomcat.manager.url}" username="${tomcat.manager.username}" password="${tomcat.manager.password}" path="/${name}" war="file:${basedir}/${name}.war"/>
    <delete file="${name}.war" quiet="true" />
</target>

<target name="undeploy" description="Remove web application">
    <undeploy url="${tomcat.manager.url}" username="${tomcat.manager.username}" password="${tomcat.manager.password}" path="/${name}" failonerror="false" />
</target>

<target name="reload" depends="build" description="Reload web application">
    <reload  url="${tomcat.manager.url}" username="${tomcat.manager.username}" password="${tomcat.manager.password}" path="/${name}"/>
</target>

<!--
<target name="test" depends="deploy" description="TEST">
    <sshexec host="${tomcat.server.url}" username="${tomcat.manager.username}" password="${tomcat.manager.password}" command="rm -f /var/lib/tomcat7/webapps/Test.war" trust="true"/>
</target>
-->
```

</project>

Thanks in advance for your help :)

**Comment by rlsutton1** [comment]
This error is important 

WARNING: The temporary file already exists [/tmp/tomcat7-tomcat7-tmp/libpi4j.so]; attempting to delete it now.his error is important

I think that when you deploy the war the second time, tomcat tries to unload the previous version of the webapp, but pi4j is still running and therefore it can't be unloaded. This in turn blocks the loading of the new install and  leads to the later exceptions.

You should add a context listener to your webapp and shutdown pi4j when tomcat destroys the context.

**Comment by PoJD** [comment]
Issue is the fact pi4j is invoking System.load to load the so lib at runtime. Running in J2EE environment however means that after redeploy of the same app, the same so lib cannot be loaded again (it is still the same VM). I temporarily solved that by putting pi4j core jar inside web container libs directly and excluded from the app. Then this class is only loaded by the web container class loader and works fine. But there is still an issue with callbacks which seem to stop working after second deploy. I suspect the so lib embedded here invokes wiringPi setup and calls to unprovision pins and unexport does not cancel the low level monitoring threads (proved by remote debugging tomcat). 

So I am now considering to fork my own pi4j and rewrite the loading of native so lib. I did it already for some other low level sensors I have in my project here :

https://github.com/PoJD/hawa

**Comment by savageautomate** [comment]
@PoJD,

If you can improve the native lib loader process, I would be happy to include it in a new build.  (Just fork and then do a pull request against 'develop' branch with your changes.)

Currently the Pi4J loader will attempt to load the system library by trying to find it in the existing lib path.  If  it can't find it, then it will attempt to extract it from the JAR as a temp file and use that.

If you could place the libpi4j.so file in a system lib path or specify the lib path for your J2EE container maybe then when Pi4J starts up it could find an existing version and not use the temp file extraction routine?

**Comment by PoJD** [comment]
Hi,

I saw the Native Lib loader logic, but seems a little overcomplicated to
me. And when I debugged it, it did not work for the temp files anyway since
it still used the same file name - JVM by default checks and libraries with
the same  name are not loaded again.

So it only worked for me when putting the lib in the sys lib of the
container. but had the other issues I mentioned in that trail.

Would you mind if I simplify it so that it would not attempt reading from
system lib, but always extract from jar instead?  It should be available in
the pi4j jar afterall all the time anyway, right.

I have somethign similar already in myproject for loading my custom so lib
(for talking to a sensor via wiringPi directly - was needed for latency).
That works fine there. Iwill try playing around and if the same logic works
also for pi4j, including the callbacks, I will for sure create a pull
request.

Happy to read you are willing to include it in the main repo!

I should get to that probably later this week and will play around later
then, so should have something ready in a week or so, will ping you if I
fail. Otherwise expect a pull request comign your  way! :)

Thanks,
PoJD
 Dne 22. 9. 2014 15:18 "Robert Savage" notifications@github.com napsal(a):

**Comment by PoJD** [comment]
Hi, pull request raised here: https://github.com/Pi4J/pi4j/pull/100

**Comment by PoJD** [comment]
As discussed in the above pull request, I have now created it against develop branch: https://github.com/Pi4J/pi4j/pull/101

**Comment by savageautomate** [comment]
Pull request merged.  Please retest using latest snapshot build.

**Comment by peyrona** [comment]
Hi guys,
I have same problem.
Did you make any progress with this issue?
Best regards.
