### ISSUE TITLE
Unable to call Gpio.wiringPiSetup()

### ISSUE THREAD

**Issue by RichoDemus** [Pi4J/pi4j-v1#87]
At the start of the code where I begin interfacing with the GPIO pins I have the following code:

if (Gpio.wiringPiSetup() == -1)
{
    logger.error(" ==>> GPIO SETUP FAILED");
    throw new GPIOSetupException("WiringPiSetup failed");
}

and usually it failes from time to time but lately it fails every single time, what can I do to troubleshoot this?

I get the following print on stdout
wiringPiSetup: mmap failed: No such file or directory

**Comment by RichoDemus** [comment]
It worked after a couple of restarts, but I'd love to find out a solution to this

**Comment by savageautomate** [comment]
Several comments related to "mmap failed" in the user comments on this WiringPi post:
https://projects.drogon.net/raspberry-pi/wiringpi/

Closing here, as this is most likely a wiringPi or environment issue.
