### ISSUE TITLE
Pi4J SPI Mode - Clock Data on falling edge

### ISSUE THREAD

**Issue by theblueone91** [Pi4J/pi4j-v1#92]
I have a DAC what i want to control with SPI. Problem is, that the RaspberryPi with Pi4J / Wiring Pi wants to clock data on rising edge of CLK - This should be the default SPI mode 0. My DAC clocks Data on falling edge of CLK - this should be SPI Mode 2.

Is there an Option to change the SPI mode?

I found this for programming in C with WiringPi:

"You can change it without too much difficulty.
You can edit wiringPiSPI.c and set spiMode to SPI_MODE_2 (near the top of the time),
or call the ioctl() to change the mode. What you need to do is set the mode to mode 2 (I think, experiment!) by
ioctl (fd, SPI_IOC_WR_MODE, &spiMode) ;
where spiMode is uint8_t that contains SPI_MODE_2, and the ‘fd’ is the number returned from wiringPiSPISetup ()
-Gordon"

Can i do this changes with Pi4J, too?

Thank you

**Comment by savageautomate** [comment]
On Feb 2, Gordon announced that WiringPi now exposes SPI modes.  
http://wiringpi.com/wiringpi-updated-for-the-new-pi-v2/

Support for SPI modes has now been added to Pi4J.
