### ISSUE TITLE
Serial: how to read binary data

### ISSUE THREAD

**Issue by ilacc1** [Pi4J/pi4j-v1#93]
It seems a very strange choice to implement serial using 'char'. In Java, char is 16-bit Unicode character - though I suspect the code assumes 8-bit US-ASCII chars. Unless I'm grossly mistaken, the current implementation does not support reading binary data at all - at least not without risking data loss.

Implementing as binary would mean text support too - as you can trivially convert from binary to text without loss (e.g. new String(data,"UTF-8") or appropriate encoding).

**Comment by saarbastler** [comment]
I found a workaround to this issue. I'm using serialDataEvent.getData().getBytes( "UTF-16" ) and use each second byte starting at index 1.

This is very hacky, I would suggest to add an additional byte array member to SerialDataEvent class.

**Comment by savageautomate** [comment]
For anyone waiting for a better serial APi for binary/byte access ....

I have been working on a new serial implementation to properly support a byte level interface for working with the data.  I suggest that you try the experimental build 1.1-SNAPSHOT.  The serial API is completely overhauled and should provide far better results when working with bytes. 

GITHUB BRANCH:
https://github.com/Pi4J/pi4j/tree/serial_enhancements

DOWNLOAD:
http://get.pi4j.com/download/pi4j-1.1-SNAPSHOT.zip

Please let me know if you find any problems ... remember it is very new and experimental :-)

**Comment by savageautomate** [comment]
Added in 1.1-SNAPSHOT build.
