### ISSUE TITLE
Missing pi4j-native-soft-float.so and pi4j-native-hard-float.so

### ISSUE THREAD

**Issue by calfater** [Pi4J/pi4j-v1#94]
When I use the 1.0-SNAPSHOT version of pi4j-native, the build failed and I got this error:

The following artifacts could not be resolved: com.pi4j:pi4j-native:so:hard-float:1.0-SNAPSHOT, com.pi4j:pi4j-native:so:soft-float:1.0-SNAPSHOT: Could not find artifact com.pi4j:pi4j-native:so:hard-float:1.0-SNAPSHOT

**Comment by savageautomate** [comment]
This issue is because I am in the middle of changing the build process and removing support for soft-float.  Options:  (A) You can pull the current pi4j sources in the develop branch and build from source.  (B) Use version 0.5 release instead temporarily or (C) wait a couple of days .. I plan on getting all the changes wrapped up and a new build deployed this weekend.

**Comment by onebeartoe** [comment]
I am seeing this issue too:

https://onebeartoe.ci.cloudbees.com/job/Photorama/2/console

Is there a workaround besides using 0.5 or building from the source code?

**Comment by savageautomate** [comment]
Ok, I have finally gotten things stable enough to deploy all the new 1.0-SNAPSHOT artifacts.  Please try again and let me know if any issues persist.  I intent to release this SNAPSHOT as as final public 1.0 release within a couple of weeks.  Thanks!

**Comment by onebeartoe** [comment]
Hi Robert,

Apologies for not getting back to you.  This one fell off my inbox somehow.

This one did ended up working with an exclude in the maven POM file.

The weird thing was that exception was just with packaging.   That is, if I
marked the Pi4J dependency as 'provided' scope, then it would package a
successfully.  Then I would just copy the Pi4J JAR with the application JAR
to the Raspberry Pi.

Thanks man.  Keep up the great work.

Roberto

**Comment by savageautomate** [comment]
Thanks for the update!

**Comment by onebeartoe** [comment]
Hi Robert,

No problem.  I wish it wasn't so late of a response.

I am now working on an I2C project with Pi4J.  It is a port of Ladyada's
Arduino code for her haptic controller.

https://github.com/adafruit/Adafruit_DRV2605_Library/blob/master/Adafruit_DRV2605.cpp

The port I have so far looks like it can obtain the device from the I2CBus,
but the actual device does not respond.

I would post on on stackoverflow.com unless you know a better place.  Can
you recommend a better place to post questions about this issue?

Thanks,

Roberto

postscript: I attached the Java port I have so far, in case you have time
to look at it.

post postscript: I ran the Adafruit example code and saw the expected
results.  So I know the hardware is working.

**Comment by savageautomate** [comment]
If its a Pi4J specific question, the best place to post is the Pi4J forums (google group)
https://groups.google.com/forum/#!forum/pi4j

Thanks, Robert

**Comment by onebeartoe** [comment]
Hi Robert,

Thanks for quick reply.

There were some calls in the Arduino C++ code to Wire.beginTransmission()
and Wire.endTrasnmission() that I didn't know how to port to Java.  I'll
revisit those calls to Wire.xxxxTransission() and if I am still having
trouble I'll post in the Pi4J forums.

Thanks again,

Roberto
