### ISSUE TITLE
Some trouble in develoment POM execution tag

### ISSUE THREAD

**Issue by leifauke** [Pi4J/pi4j-v1#97]
Hi,

When setting development branch the POM report error on '<parent>' tag and '<Execution>' tags

Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-dependency-plugin:2.8:copy (execution: copy-license, phase: validate)   pom.xml /pi4j-core  line 10 

Is there a quick fix to this ? 

(it do not happen in master)

And thanks for a very nice piece of software !! 

regards Leif H.

**Comment by savageautomate** [comment]
HI Leif,

What version of the JVM and of Maven are you using?

I just tested using JDK8 and Maven 3.0.5 (and 3.2.1 on another machine)

```
git clone -bdevelop https://github.com/Pi4J/pi4j.git
cd pi4j
mvn clean install
```

This worked fine for me on OSX and Ubuntu.

**Comment by leifauke** [comment]
Hi,

Its seems to be a eclipse (Version: Kepler Service Release 2) problem. Running mvn batch seems working except for the distribution project. This fails with exception.

Tnx. (figure out later why eclipse don't work)

:)

(I just started study and trial the Pi4J)

Regards Leif H.

**Comment by savageautomate** [comment]
This thread may give some insight to the eclipse m3e issues:
http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

I have updated the sources to address the error with the distribution project.  Pull the latest and try again from CLI.   Thanks!
