### ISSUE TITLE
Failed to load library [pi4j]

### ISSUE THREAD

**Issue by jfrancoya** [Pi4J/pi4j-v1#98]
Over a Raspberry PI B+ with a RASPBIAN Debian Wheezy, Version:September 2014 Release date:2014-09-09 just deployed, with the oracle jdk8 insttaled, I have deployed the PI4J with the prefferred install procedure (curl -s get.pi4j.com | sudo bash). After that y compile all the examples an then run the 
java -classpath .:classes:/opt/pi4j/lib/'*' BlinkGpioExample 
command getting this messages:

<--Pi4J--> GPIO Blink Example ... started.
Sep 17, 2014 11:58:34 PM com.pi4j.util.NativeLibraryLoader load
SEVERE: Failed to load library [pi4j] using the System.load(file) method using embedded resource file: [jar:file:/opt/pi4j/lib/pi4j-core.jar!/lib/libpi4j.so]
Sep 17, 2014 11:58:34 PM com.pi4j.util.NativeLibraryLoader load
SEVERE: ERROR:  The native library [pi4j : libpi4j.so] could not be found in the JVM library path nor could it be loaded from the embedded JAR resource file; you may need to explicitly define the library path '-Djava.library.path' where this native library can be found.
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.pi4j.wiringpi.Gpio.wiringPiSetup()I
    at com.pi4j.wiringpi.Gpio.wiringPiSetup(Native Method)
    at com.pi4j.io.gpio.RaspiGpioProvider.<init>(RaspiGpioProvider.java:48)
    at com.pi4j.io.gpio.GpioFactory.getDefaultProvider(GpioFactory.java:104)
    at com.pi4j.io.gpio.impl.GpioControllerImpl.<init>(GpioControllerImpl.java:67)
    at com.pi4j.io.gpio.GpioFactory.getInstance(GpioFactory.java:87)
    at BlinkGpioExample.main(BlinkGpioExample.java:55)

Best regards

**Comment by jfrancoya** [comment]
Any sugestion?

**Comment by savageautomate** [comment]
testing it here now .. standby ...

**Comment by savageautomate** [comment]
So ... I encountered the same issue on a clean image.  It looks like wiringPi did not get statically compiled into the Pi4J native JNI library.  (whoops).  I will look into that issue.  

For the moment, please install wiringPi via the instructions here: 
http://wiringpi.com/download-and-install/

Once I installed wiringPi (cloned repo and build) then Pi4J started working.

**Comment by savageautomate** [comment]
Fixed and deployed new snapshot build.  
To update your system, please run the following commands:

```
sudo apt-get remove pi4j
sudo apt-get update
sudo apt-get install pi4j
```
