### ISSUE TITLE
PiFace won't switch LEDs

### ISSUE THREAD

**Issue by geohuk** [Pi4J/pi4j-v1#99]
Hello, I've got a RaspberryPi Model B with PiFace Digital and pi4j release 0.0.5.
I am having issues switching the LEDs of the PiFace. No exception or error log seems to be thrown.
A SwitchListener on the buttons works just fine, so I assume my PiFace is not damaged.
Can anyone else confirm? Perhaps this was fixed in the latest snapshot?

Kind Regards,
Georgi

**Comment by savageautomate** [comment]
Please try the newer version in 1.0-SNAPSHOT:
http://pi4j.com/download.html

**Comment by savageautomate** [comment]
CLOSED; I have tested this with the latest 1.0-SNAPSHOT and it is working for me :-)

**Comment by geohuk** [comment]
Yeah, it was an issue on my side. Cheers.
